<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 PCA | BioSakshat - Free Study Materials</title>
  <meta name="description" content="+++" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 PCA | BioSakshat - Free Study Materials" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="+++" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 PCA | BioSakshat - Free Study Materials" />
  
  <meta name="twitter:description" content="+++" />
  

<meta name="author" content="By Priyabrata Panigrahi and Pandurang Kolekar" />


<meta name="date" content="2019-08-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="clustering.html">
<link rel="next" href="network-analysis.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/vis-4.20.1/vis.css" rel="stylesheet" />
<script src="libs/vis-4.20.1/vis.min.js"></script>
<script src="libs/visNetwork-binding-2.0.7/visNetwork.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BioSakshat</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Site navigation</a></li>
<li class="chapter" data-level="2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html"><i class="fa fa-check"></i><b>2</b> Data types and Data structures</a><ul>
<li class="chapter" data-level="2.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#lets-begin"><i class="fa fa-check"></i><b>2.1</b> Lets Begin</a></li>
<li class="chapter" data-level="2.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#expression"><i class="fa fa-check"></i><b>2.2</b> Expression</a></li>
<li class="chapter" data-level="2.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#assignment"><i class="fa fa-check"></i><b>2.3</b> Assignment</a></li>
<li class="chapter" data-level="2.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#working-directory"><i class="fa fa-check"></i><b>2.4</b> Working directory</a></li>
<li class="chapter" data-level="2.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#list-of-objects-in-workspaceenvironment"><i class="fa fa-check"></i><b>2.5</b> List of objects in workspace/environment</a></li>
<li class="chapter" data-level="2.6" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#getting-help-in-r"><i class="fa fa-check"></i><b>2.6</b> getting help in R</a><ul>
<li class="chapter" data-level="2.6.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#some-things-to-remember"><i class="fa fa-check"></i><b>2.6.1</b> Some things to Remember</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#data-types"><i class="fa fa-check"></i><b>2.7</b> Data Types</a></li>
<li class="chapter" data-level="2.8" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#data-structures"><i class="fa fa-check"></i><b>2.8</b> Data Structures</a></li>
<li class="chapter" data-level="2.9" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#vector"><i class="fa fa-check"></i><b>2.9</b> Vector</a><ul>
<li class="chapter" data-level="2.9.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#creating-a-vector"><i class="fa fa-check"></i><b>2.9.1</b> Creating a vector</a></li>
<li class="chapter" data-level="2.9.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-vector-of-one-element"><i class="fa fa-check"></i><b>2.9.2</b> Create Vector of one element</a></li>
<li class="chapter" data-level="2.9.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-vector-using-range-operator"><i class="fa fa-check"></i><b>2.9.3</b> Create Vector using Range operator (:)</a></li>
<li class="chapter" data-level="2.9.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-vector-using-c"><i class="fa fa-check"></i><b>2.9.4</b> Create Vector using c()</a></li>
<li class="chapter" data-level="2.9.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#seq-function"><i class="fa fa-check"></i><b>2.9.5</b> seq() function</a></li>
<li class="chapter" data-level="2.9.6" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#rep-function"><i class="fa fa-check"></i><b>2.9.6</b> rep() function</a></li>
<li class="chapter" data-level="2.9.7" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#sample-function"><i class="fa fa-check"></i><b>2.9.7</b> sample() function</a></li>
<li class="chapter" data-level="2.9.8" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#rnorm-function"><i class="fa fa-check"></i><b>2.9.8</b> rnorm() function</a></li>
<li class="chapter" data-level="2.9.9" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetching-elements-from-a-vector"><i class="fa fa-check"></i><b>2.9.9</b> Fetching elements from a vector</a></li>
<li class="chapter" data-level="2.9.10" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#delete-elements-from-a-vector"><i class="fa fa-check"></i><b>2.9.10</b> Delete element(s) from a vector</a></li>
<li class="chapter" data-level="2.9.11" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#add-elements-to-existing-vector"><i class="fa fa-check"></i><b>2.9.11</b> Add element(s) to existing vector</a></li>
<li class="chapter" data-level="2.9.12" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#replace-elements-in-existing-vector"><i class="fa fa-check"></i><b>2.9.12</b> Replace elements in existing vector</a></li>
<li class="chapter" data-level="2.9.13" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#inbuilt-functions-for-numeric-vector"><i class="fa fa-check"></i><b>2.9.13</b> Inbuilt functions for numeric vector</a></li>
<li class="chapter" data-level="2.9.14" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#correlation-using-cor"><i class="fa fa-check"></i><b>2.9.14</b> Correlation using cor()</a></li>
<li class="chapter" data-level="2.9.15" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#set-operations"><i class="fa fa-check"></i><b>2.9.15</b> Set operations</a></li>
<li class="chapter" data-level="2.9.16" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#arithmetic-expressions"><i class="fa fa-check"></i><b>2.9.16</b> Arithmetic expressions</a></li>
<li class="chapter" data-level="2.9.17" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#arithmetic-operations-on-vector"><i class="fa fa-check"></i><b>2.9.17</b> Arithmetic operations on vector</a></li>
<li class="chapter" data-level="2.9.18" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#operator-precedence"><i class="fa fa-check"></i><b>2.9.18</b> Operator precedence</a></li>
<li class="chapter" data-level="2.9.19" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#conditional-statements"><i class="fa fa-check"></i><b>2.9.19</b> Conditional statements</a></li>
<li class="chapter" data-level="2.9.20" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-for-missing-values"><i class="fa fa-check"></i><b>2.9.20</b> Check for missing values</a></li>
<li class="chapter" data-level="2.9.21" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-data-types-and-data-structures"><i class="fa fa-check"></i><b>2.9.21</b> Check data types and data structures</a></li>
<li class="chapter" data-level="2.9.22" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#implicit-data-type-conversion"><i class="fa fa-check"></i><b>2.9.22</b> Implicit Data type conversion</a></li>
<li class="chapter" data-level="2.9.23" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#character-vector-and-related-functions"><i class="fa fa-check"></i><b>2.9.23</b> Character vector and related functions</a></li>
<li class="chapter" data-level="2.9.24" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#explicit-data-type-conversion"><i class="fa fa-check"></i><b>2.9.24</b> Explicit Data Type Conversion</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#matrix"><i class="fa fa-check"></i><b>2.10</b> Matrix</a><ul>
<li class="chapter" data-level="2.10.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-a-matrix-from-vector-using-dim-attributes"><i class="fa fa-check"></i><b>2.10.1</b> Create a matrix from vector using dim attributes</a></li>
<li class="chapter" data-level="2.10.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-matrix-using-matrix"><i class="fa fa-check"></i><b>2.10.2</b> Create matrix using matrix()</a></li>
<li class="chapter" data-level="2.10.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#functions-that-can-be-applied-to-a-matrix"><i class="fa fa-check"></i><b>2.10.3</b> Functions that can be applied to a matrix</a></li>
<li class="chapter" data-level="2.10.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#assign-columnrow-names"><i class="fa fa-check"></i><b>2.10.4</b> Assign column/row names</a></li>
<li class="chapter" data-level="2.10.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-elements-from-a-matrix-using-indices"><i class="fa fa-check"></i><b>2.10.5</b> Fetch elements from a matrix using indices</a></li>
<li class="chapter" data-level="2.10.6" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-element-using-index-matrix"><i class="fa fa-check"></i><b>2.10.6</b> Fetch element using index matrix</a></li>
<li class="chapter" data-level="2.10.7" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-elements-from-a-matrix-using-row-and-column-names"><i class="fa fa-check"></i><b>2.10.7</b> Fetch elements from a matrix using row and column names</a></li>
<li class="chapter" data-level="2.10.8" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#insert-rows-and-columns-by-rbind-and-cbind"><i class="fa fa-check"></i><b>2.10.8</b> Insert rows and columns by rbind() and cbind()</a></li>
<li class="chapter" data-level="2.10.9" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-matrix-using-rbind-and-cbind"><i class="fa fa-check"></i><b>2.10.9</b> Create matrix using rbind() and cbind()</a></li>
<li class="chapter" data-level="2.10.10" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#delete-rows-and-columns"><i class="fa fa-check"></i><b>2.10.10</b> Delete row(s) and column(s)</a></li>
<li class="chapter" data-level="2.10.11" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-for-matrix"><i class="fa fa-check"></i><b>2.10.11</b> Check for matrix</a></li>
<li class="chapter" data-level="2.10.12" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#conditional-statements-on-matrix"><i class="fa fa-check"></i><b>2.10.12</b> Conditional statements on matrix</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#data-frame"><i class="fa fa-check"></i><b>2.11</b> Data Frame</a><ul>
<li class="chapter" data-level="2.11.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-a-data-frame"><i class="fa fa-check"></i><b>2.11.1</b> Create a data frame</a></li>
<li class="chapter" data-level="2.11.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-values-from-a-data-frame"><i class="fa fa-check"></i><b>2.11.2</b> Fetch values from a data frame</a></li>
<li class="chapter" data-level="2.11.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#insert-column-to-data-frame"><i class="fa fa-check"></i><b>2.11.3</b> Insert column to data frame</a></li>
<li class="chapter" data-level="2.11.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#delete-column-or-row-from-data-frame"><i class="fa fa-check"></i><b>2.11.4</b> Delete column or row from data frame</a></li>
<li class="chapter" data-level="2.11.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-for-data-frame"><i class="fa fa-check"></i><b>2.11.5</b> Check for data frame</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#list"><i class="fa fa-check"></i><b>2.12</b> List</a><ul>
<li class="chapter" data-level="2.12.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#access-component-of-list-using-notation"><i class="fa fa-check"></i><b>2.12.1</b> Access component of list using $ notation</a></li>
<li class="chapter" data-level="2.12.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#access-component-of-list-using"><i class="fa fa-check"></i><b>2.12.2</b> Access component of list using []</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html"><i class="fa fa-check"></i><b>3</b> If/For/Function/IO</a><ul>
<li class="chapter" data-level="3.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#conditional-statements-1"><i class="fa fa-check"></i><b>3.1</b> Conditional statements</a></li>
<li class="chapter" data-level="3.2" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#repetitive-execution-using-for-loop"><i class="fa fa-check"></i><b>3.2</b> Repetitive execution using for loop</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#task"><i class="fa fa-check"></i><b>3.2.1</b> Task</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#functions"><i class="fa fa-check"></i><b>3.3</b> Functions</a><ul>
<li class="chapter" data-level="3.3.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#define-function"><i class="fa fa-check"></i><b>3.3.1</b> Define function</a></li>
<li class="chapter" data-level="3.3.2" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#call-function"><i class="fa fa-check"></i><b>3.3.2</b> Call function</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#file-io"><i class="fa fa-check"></i><b>3.4</b> File IO</a><ul>
<li class="chapter" data-level="3.4.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#the-read.table-function"><i class="fa fa-check"></i><b>3.4.1</b> The read.table() function</a></li>
<li class="chapter" data-level="3.4.2" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-data"><i class="fa fa-check"></i><b>3.4.2</b> Read data</a></li>
<li class="chapter" data-level="3.4.3" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#about-headertrue-parameter"><i class="fa fa-check"></i><b>3.4.3</b> About header=TRUE parameter</a></li>
<li class="chapter" data-level="3.4.4" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#about-stringsasfactors-false-parameter"><i class="fa fa-check"></i><b>3.4.4</b> About stringsAsFactors = FALSE parameter</a></li>
<li class="chapter" data-level="3.4.5" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#other-useful-parameters"><i class="fa fa-check"></i><b>3.4.5</b> Other useful parameters:</a></li>
<li class="chapter" data-level="3.4.6" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-file-with-unequal-columns-in-first-row-using-read.table."><i class="fa fa-check"></i><b>3.4.6</b> Read file with unequal columns in first row using read.table.</a></li>
<li class="chapter" data-level="3.4.7" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-file-consisting-of-comments-blank-lines-null-values"><i class="fa fa-check"></i><b>3.4.7</b> Read file consisting of comments, blank lines, null values</a></li>
<li class="chapter" data-level="3.4.8" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-csv-file-read.csv"><i class="fa fa-check"></i><b>3.4.8</b> Read csv file read.csv()</a></li>
<li class="chapter" data-level="3.4.9" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#reading-data-from-excel-file"><i class="fa fa-check"></i><b>3.4.9</b> Reading data from excel file</a></li>
<li class="chapter" data-level="3.4.10" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-data-using-readlines"><i class="fa fa-check"></i><b>3.4.10</b> Read data using readLines()</a></li>
<li class="chapter" data-level="3.4.11" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-data-using-clipboard-feature"><i class="fa fa-check"></i><b>3.4.11</b> Read data using clipboard feature</a></li>
<li class="chapter" data-level="3.4.12" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#view-data-frame-using-view"><i class="fa fa-check"></i><b>3.4.12</b> View data frame using View()</a></li>
<li class="chapter" data-level="3.4.13" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#edit-data-frame-using-edit"><i class="fa fa-check"></i><b>3.4.13</b> Edit data frame using edit()</a></li>
<li class="chapter" data-level="3.4.14" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#write-r-data-frames-in-a-file-using-write.table"><i class="fa fa-check"></i><b>3.4.14</b> Write R data frames in a file using write.table()</a></li>
<li class="chapter" data-level="3.4.15" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#write-using-cat"><i class="fa fa-check"></i><b>3.4.15</b> Write using cat()</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-manipulation.html"><a href="data-manipulation.html"><i class="fa fa-check"></i><b>4</b> Data Manipulation</a><ul>
<li class="chapter" data-level="4.1" data-path="data-manipulation.html"><a href="data-manipulation.html#the-apply-function"><i class="fa fa-check"></i><b>4.1</b> The apply() function</a></li>
<li class="chapter" data-level="4.2" data-path="data-manipulation.html"><a href="data-manipulation.html#sapply-function"><i class="fa fa-check"></i><b>4.2</b> sapply() function</a></li>
<li class="chapter" data-level="4.3" data-path="data-manipulation.html"><a href="data-manipulation.html#lapply-function"><i class="fa fa-check"></i><b>4.3</b> lapply() function</a></li>
<li class="chapter" data-level="4.4" data-path="data-manipulation.html"><a href="data-manipulation.html#dplyr-package"><i class="fa fa-check"></i><b>4.4</b> dplyr package</a><ul>
<li class="chapter" data-level="4.4.1" data-path="data-manipulation.html"><a href="data-manipulation.html#load-dplyr-library"><i class="fa fa-check"></i><b>4.4.1</b> Load dplyr library</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-manipulation.html"><a href="data-manipulation.html#load-gene-expression-data"><i class="fa fa-check"></i><b>4.4.2</b> Load Gene Expression Data</a></li>
<li class="chapter" data-level="4.4.3" data-path="data-manipulation.html"><a href="data-manipulation.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>4.4.3</b> Filter rows with filter()</a></li>
<li class="chapter" data-level="4.4.4" data-path="data-manipulation.html"><a href="data-manipulation.html#piping-using"><i class="fa fa-check"></i><b>4.4.4</b> Piping using %&gt;%</a></li>
<li class="chapter" data-level="4.4.5" data-path="data-manipulation.html"><a href="data-manipulation.html#arrange-rows-with-arrange"><i class="fa fa-check"></i><b>4.4.5</b> Arrange rows with arrange()</a></li>
<li class="chapter" data-level="4.4.6" data-path="data-manipulation.html"><a href="data-manipulation.html#select-rows-position-wise-using-slice"><i class="fa fa-check"></i><b>4.4.6</b> Select rows position wise using slice()</a></li>
<li class="chapter" data-level="4.4.7" data-path="data-manipulation.html"><a href="data-manipulation.html#select-column-using-select"><i class="fa fa-check"></i><b>4.4.7</b> Select column using select()</a></li>
<li class="chapter" data-level="4.4.8" data-path="data-manipulation.html"><a href="data-manipulation.html#extract-unique-rows-using-distinct"><i class="fa fa-check"></i><b>4.4.8</b> Extract unique rows using distinct()</a></li>
<li class="chapter" data-level="4.4.9" data-path="data-manipulation.html"><a href="data-manipulation.html#add-new-columns-with-mutate-and-transmute-function"><i class="fa fa-check"></i><b>4.4.9</b> Add new columns with mutate() and transmute() function</a></li>
<li class="chapter" data-level="4.4.10" data-path="data-manipulation.html"><a href="data-manipulation.html#summarise-values-with-summarise"><i class="fa fa-check"></i><b>4.4.10</b> Summarise values with summarise()</a></li>
<li class="chapter" data-level="4.4.11" data-path="data-manipulation.html"><a href="data-manipulation.html#grouped-operations"><i class="fa fa-check"></i><b>4.4.11</b> Grouped operations</a></li>
<li class="chapter" data-level="4.4.12" data-path="data-manipulation.html"><a href="data-manipulation.html#joins-two-table"><i class="fa fa-check"></i><b>4.4.12</b> Joins two table</a></li>
<li class="chapter" data-level="4.4.13" data-path="data-manipulation.html"><a href="data-manipulation.html#references"><i class="fa fa-check"></i><b>4.4.13</b> References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>5</b> Data Visualization</a><ul>
<li class="chapter" data-level="5.1" data-path="data-visualization.html"><a href="data-visualization.html#base-graphics"><i class="fa fa-check"></i><b>5.1</b> Base Graphics</a><ul>
<li class="chapter" data-level="5.1.1" data-path="data-visualization.html"><a href="data-visualization.html#simple-scatter-plot"><i class="fa fa-check"></i><b>5.1.1</b> Simple scatter plot</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-visualization.html"><a href="data-visualization.html#saving-plot"><i class="fa fa-check"></i><b>5.1.2</b> Saving plot</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-visualization.html"><a href="data-visualization.html#add-titlesubtitlex-axis-labely-axis-label-to-plot"><i class="fa fa-check"></i><b>5.1.3</b> Add title/subtitle/x-axis label/y-axis label to plot</a></li>
<li class="chapter" data-level="5.1.4" data-path="data-visualization.html"><a href="data-visualization.html#increase-line-thickness"><i class="fa fa-check"></i><b>5.1.4</b> Increase line thickness</a></li>
<li class="chapter" data-level="5.1.5" data-path="data-visualization.html"><a href="data-visualization.html#assign-color-to-lines-and-points"><i class="fa fa-check"></i><b>5.1.5</b> Assign color to lines and points</a></li>
<li class="chapter" data-level="5.1.6" data-path="data-visualization.html"><a href="data-visualization.html#explore-built-in-colors"><i class="fa fa-check"></i><b>5.1.6</b> Explore built-in colors</a></li>
<li class="chapter" data-level="5.1.7" data-path="data-visualization.html"><a href="data-visualization.html#explore-different-symbols"><i class="fa fa-check"></i><b>5.1.7</b> Explore different symbols</a></li>
<li class="chapter" data-level="5.1.8" data-path="data-visualization.html"><a href="data-visualization.html#explore-different-line-types"><i class="fa fa-check"></i><b>5.1.8</b> Explore different line types</a></li>
<li class="chapter" data-level="5.1.9" data-path="data-visualization.html"><a href="data-visualization.html#rescale-the-x-axis-and-y-axis"><i class="fa fa-check"></i><b>5.1.9</b> Rescale the x-axis and y-axis</a></li>
<li class="chapter" data-level="5.1.10" data-path="data-visualization.html"><a href="data-visualization.html#magnification-of-labels-and-symbols"><i class="fa fa-check"></i><b>5.1.10</b> Magnification of labels and symbols</a></li>
<li class="chapter" data-level="5.1.11" data-path="data-visualization.html"><a href="data-visualization.html#explore-bty-box-type"><i class="fa fa-check"></i><b>5.1.11</b> Explore bty (box type)</a></li>
<li class="chapter" data-level="5.1.12" data-path="data-visualization.html"><a href="data-visualization.html#explore-las-style-of-axis-labels"><i class="fa fa-check"></i><b>5.1.12</b> Explore las (style of axis labels)</a></li>
<li class="chapter" data-level="5.1.13" data-path="data-visualization.html"><a href="data-visualization.html#explore-col.axis-col.lab-col.main-col.sub-parameters"><i class="fa fa-check"></i><b>5.1.13</b> Explore col.axis, col.lab, col.main, col.sub parameters</a></li>
<li class="chapter" data-level="5.1.14" data-path="data-visualization.html"><a href="data-visualization.html#low-level-plotting-functions-lines"><i class="fa fa-check"></i><b>5.1.14</b> Low level plotting functions (lines)</a></li>
<li class="chapter" data-level="5.1.15" data-path="data-visualization.html"><a href="data-visualization.html#low-level-plotting-functions-legend"><i class="fa fa-check"></i><b>5.1.15</b> Low level plotting functions (legend)</a></li>
<li class="chapter" data-level="5.1.16" data-path="data-visualization.html"><a href="data-visualization.html#adding-texts-to-existing-plot-text"><i class="fa fa-check"></i><b>5.1.16</b> Adding texts to existing plot (text)</a></li>
<li class="chapter" data-level="5.1.17" data-path="data-visualization.html"><a href="data-visualization.html#explore-line-plot"><i class="fa fa-check"></i><b>5.1.17</b> Explore Line Plot</a></li>
<li class="chapter" data-level="5.1.18" data-path="data-visualization.html"><a href="data-visualization.html#explore-simple-bar-plot"><i class="fa fa-check"></i><b>5.1.18</b> Explore simple Bar plot</a></li>
<li class="chapter" data-level="5.1.19" data-path="data-visualization.html"><a href="data-visualization.html#explore-stacked-bar-plot"><i class="fa fa-check"></i><b>5.1.19</b> Explore stacked bar plot</a></li>
<li class="chapter" data-level="5.1.20" data-path="data-visualization.html"><a href="data-visualization.html#grouped-bar-plots"><i class="fa fa-check"></i><b>5.1.20</b> Grouped Bar plots</a></li>
<li class="chapter" data-level="5.1.21" data-path="data-visualization.html"><a href="data-visualization.html#histogram"><i class="fa fa-check"></i><b>5.1.21</b> Histogram</a></li>
<li class="chapter" data-level="5.1.22" data-path="data-visualization.html"><a href="data-visualization.html#density-plot"><i class="fa fa-check"></i><b>5.1.22</b> Density plot</a></li>
<li class="chapter" data-level="5.1.23" data-path="data-visualization.html"><a href="data-visualization.html#plot-density-plot-of-two-distributions"><i class="fa fa-check"></i><b>5.1.23</b> Plot density plot of two distributions</a></li>
<li class="chapter" data-level="5.1.24" data-path="data-visualization.html"><a href="data-visualization.html#box-plots"><i class="fa fa-check"></i><b>5.1.24</b> Box plots</a></li>
<li class="chapter" data-level="5.1.25" data-path="data-visualization.html"><a href="data-visualization.html#pie-chart"><i class="fa fa-check"></i><b>5.1.25</b> Pie chart</a></li>
<li class="chapter" data-level="5.1.26" data-path="data-visualization.html"><a href="data-visualization.html#venn-diagram"><i class="fa fa-check"></i><b>5.1.26</b> Venn diagram</a></li>
<li class="chapter" data-level="5.1.27" data-path="data-visualization.html"><a href="data-visualization.html#heatmap"><i class="fa fa-check"></i><b>5.1.27</b> Heatmap</a></li>
<li class="chapter" data-level="5.1.28" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plot-matrices"><i class="fa fa-check"></i><b>5.1.28</b> Scatter plot Matrices</a></li>
<li class="chapter" data-level="5.1.29" data-path="data-visualization.html"><a href="data-visualization.html#ballon-plot"><i class="fa fa-check"></i><b>5.1.29</b> Ballon plot</a></li>
<li class="chapter" data-level="5.1.30" data-path="data-visualization.html"><a href="data-visualization.html#multi-panel-plots"><i class="fa fa-check"></i><b>5.1.30</b> Multi panel plots</a></li>
<li class="chapter" data-level="5.1.31" data-path="data-visualization.html"><a href="data-visualization.html#pca-prinicipal-component-analysis"><i class="fa fa-check"></i><b>5.1.31</b> PCA (Prinicipal Component Analysis)</a></li>
<li class="chapter" data-level="5.1.32" data-path="data-visualization.html"><a href="data-visualization.html#classical-metric-multidimensional-scaling"><i class="fa fa-check"></i><b>5.1.32</b> Classical (Metric) Multidimensional Scaling</a></li>
<li class="chapter" data-level="5.1.33" data-path="data-visualization.html"><a href="data-visualization.html#plotting-k-means"><i class="fa fa-check"></i><b>5.1.33</b> Plotting K-means</a></li>
<li class="chapter" data-level="5.1.34" data-path="data-visualization.html"><a href="data-visualization.html#dendrogram"><i class="fa fa-check"></i><b>5.1.34</b> Dendrogram</a></li>
<li class="chapter" data-level="5.1.35" data-path="data-visualization.html"><a href="data-visualization.html#network-graphs"><i class="fa fa-check"></i><b>5.1.35</b> Network graphs</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-visualization.html"><a href="data-visualization.html#plot-using-ggplot2"><i class="fa fa-check"></i><b>5.2</b> Plot using ggplot2</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>5.2.1</b> Scatter plot</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-visualization.html"><a href="data-visualization.html#add-geom_point-layer"><i class="fa fa-check"></i><b>5.2.2</b> Add geom_point() layer</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-visualization.html"><a href="data-visualization.html#add-geom_smooth-layer-linear-modeling"><i class="fa fa-check"></i><b>5.2.3</b> Add geom_smooth() layer, linear modeling</a></li>
<li class="chapter" data-level="5.2.4" data-path="data-visualization.html"><a href="data-visualization.html#explore-aesthetic-parameter-col"><i class="fa fa-check"></i><b>5.2.4</b> Explore aesthetic parameter “col”</a></li>
<li class="chapter" data-level="5.2.5" data-path="data-visualization.html"><a href="data-visualization.html#assign-aes-to-individual-layer"><i class="fa fa-check"></i><b>5.2.5</b> Assign aes() to individual layer</a></li>
<li class="chapter" data-level="5.2.6" data-path="data-visualization.html"><a href="data-visualization.html#explore-aesthetic-parameter-shape"><i class="fa fa-check"></i><b>5.2.6</b> Explore aesthetic parameter “shape”</a></li>
<li class="chapter" data-level="5.2.7" data-path="data-visualization.html"><a href="data-visualization.html#add-axis-lables-and-plot-title-using-labs"><i class="fa fa-check"></i><b>5.2.7</b> Add axis lables and plot title using labs()</a></li>
<li class="chapter" data-level="5.2.8" data-path="data-visualization.html"><a href="data-visualization.html#change-color-pelette"><i class="fa fa-check"></i><b>5.2.8</b> Change color pelette</a></li>
<li class="chapter" data-level="5.2.9" data-path="data-visualization.html"><a href="data-visualization.html#save-the-ggplot-object-and-then-print."><i class="fa fa-check"></i><b>5.2.9</b> Save the ggplot object and then print.</a></li>
<li class="chapter" data-level="5.2.10" data-path="data-visualization.html"><a href="data-visualization.html#the-theme"><i class="fa fa-check"></i><b>5.2.10</b> The Theme</a></li>
<li class="chapter" data-level="5.2.11" data-path="data-visualization.html"><a href="data-visualization.html#adjusting-the-legend-title"><i class="fa fa-check"></i><b>5.2.11</b> Adjusting the legend title</a></li>
<li class="chapter" data-level="5.2.12" data-path="data-visualization.html"><a href="data-visualization.html#facet_wrap"><i class="fa fa-check"></i><b>5.2.12</b> Facet_wrap</a></li>
<li class="chapter" data-level="5.2.13" data-path="data-visualization.html"><a href="data-visualization.html#bar-charts"><i class="fa fa-check"></i><b>5.2.13</b> Bar charts</a></li>
<li class="chapter" data-level="5.2.14" data-path="data-visualization.html"><a href="data-visualization.html#density-plot-1"><i class="fa fa-check"></i><b>5.2.14</b> Density plot</a></li>
<li class="chapter" data-level="5.2.15" data-path="data-visualization.html"><a href="data-visualization.html#box-plot"><i class="fa fa-check"></i><b>5.2.15</b> Box plot</a></li>
<li class="chapter" data-level="5.2.16" data-path="data-visualization.html"><a href="data-visualization.html#references-1"><i class="fa fa-check"></i><b>5.2.16</b> References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bioconductor.html"><a href="bioconductor.html"><i class="fa fa-check"></i><b>6</b> Bioconductor</a><ul>
<li class="chapter" data-level="6.1" data-path="bioconductor.html"><a href="bioconductor.html#introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="bioconductor.html"><a href="bioconductor.html#install"><i class="fa fa-check"></i><b>6.1.1</b> Install</a></li>
<li class="chapter" data-level="6.1.2" data-path="bioconductor.html"><a href="bioconductor.html#explore-bioconductor-tutorials"><i class="fa fa-check"></i><b>6.1.2</b> Explore Bioconductor Tutorials</a></li>
<li class="chapter" data-level="6.1.3" data-path="bioconductor.html"><a href="bioconductor.html#explore-course-and-conferences-materials"><i class="fa fa-check"></i><b>6.1.3</b> Explore course and conferences materials</a></li>
<li class="chapter" data-level="6.1.4" data-path="bioconductor.html"><a href="bioconductor.html#explore-and-search-for-package-using-biocviews"><i class="fa fa-check"></i><b>6.1.4</b> Explore and Search for package using BiocViews</a></li>
<li class="chapter" data-level="6.1.5" data-path="bioconductor.html"><a href="bioconductor.html#bioconductor-forum"><i class="fa fa-check"></i><b>6.1.5</b> Bioconductor Forum</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bioconductor.html"><a href="bioconductor.html#explore-maftools"><i class="fa fa-check"></i><b>6.2</b> Explore Maftools</a><ul>
<li class="chapter" data-level="6.2.1" data-path="bioconductor.html"><a href="bioconductor.html#about-maftools"><i class="fa fa-check"></i><b>6.2.1</b> About MAFtools</a></li>
<li class="chapter" data-level="6.2.2" data-path="bioconductor.html"><a href="bioconductor.html#about-maf-file"><i class="fa fa-check"></i><b>6.2.2</b> About MAF file</a></li>
<li class="chapter" data-level="6.2.3" data-path="bioconductor.html"><a href="bioconductor.html#install-maftools."><i class="fa fa-check"></i><b>6.2.3</b> Install maftools.</a></li>
<li class="chapter" data-level="6.2.4" data-path="bioconductor.html"><a href="bioconductor.html#load-maftools-library"><i class="fa fa-check"></i><b>6.2.4</b> Load maftools library</a></li>
<li class="chapter" data-level="6.2.5" data-path="bioconductor.html"><a href="bioconductor.html#read-example-maf-file"><i class="fa fa-check"></i><b>6.2.5</b> Read example maf file</a></li>
<li class="chapter" data-level="6.2.6" data-path="bioconductor.html"><a href="bioconductor.html#print-maf-object"><i class="fa fa-check"></i><b>6.2.6</b> Print maf object</a></li>
<li class="chapter" data-level="6.2.7" data-path="bioconductor.html"><a href="bioconductor.html#structure-of-maf-object"><i class="fa fa-check"></i><b>6.2.7</b> Structure of maf object</a></li>
<li class="chapter" data-level="6.2.8" data-path="bioconductor.html"><a href="bioconductor.html#shows-sample-summry."><i class="fa fa-check"></i><b>6.2.8</b> Shows sample summry.</a></li>
<li class="chapter" data-level="6.2.9" data-path="bioconductor.html"><a href="bioconductor.html#show-frequently-mutated-genes."><i class="fa fa-check"></i><b>6.2.9</b> Show frequently mutated genes.</a></li>
<li class="chapter" data-level="6.2.10" data-path="bioconductor.html"><a href="bioconductor.html#shows-all-fields-in-maf"><i class="fa fa-check"></i><b>6.2.10</b> Shows all fields in MAF</a></li>
<li class="chapter" data-level="6.2.11" data-path="bioconductor.html"><a href="bioconductor.html#plotting-maf-summary"><i class="fa fa-check"></i><b>6.2.11</b> Plotting MAF summary</a></li>
<li class="chapter" data-level="6.2.12" data-path="bioconductor.html"><a href="bioconductor.html#oncoplots"><i class="fa fa-check"></i><b>6.2.12</b> Oncoplots</a></li>
<li class="chapter" data-level="6.2.13" data-path="bioconductor.html"><a href="bioconductor.html#transition-and-transversions."><i class="fa fa-check"></i><b>6.2.13</b> Transition and Transversions.</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="bioconductor.html"><a href="bioconductor.html#explore-cummerbund-for-diffrential-gene-expression-analysis"><i class="fa fa-check"></i><b>6.3</b> Explore cummeRbund for Diffrential Gene Expression Analysis</a></li>
<li class="chapter" data-level="6.4" data-path="bioconductor.html"><a href="bioconductor.html#references-2"><i class="fa fa-check"></i><b>6.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html"><i class="fa fa-check"></i><b>7</b> R Case study and Tasks</a><ul>
<li class="chapter" data-level="7.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#case-study1-gene-expression-data-analysis"><i class="fa fa-check"></i><b>7.1</b> Case study1: Gene Expression Data Analysis</a><ul>
<li class="chapter" data-level="7.1.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#experimental-setup"><i class="fa fa-check"></i><b>7.1.1</b> Experimental setup</a></li>
<li class="chapter" data-level="7.1.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#objective"><i class="fa fa-check"></i><b>7.1.2</b> Objective</a></li>
<li class="chapter" data-level="7.1.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#steps"><i class="fa fa-check"></i><b>7.1.3</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#case-study1-solution"><i class="fa fa-check"></i><b>7.2</b> Case study1: Solution</a></li>
<li class="chapter" data-level="7.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#tasks"><i class="fa fa-check"></i><b>7.3</b> Tasks</a><ul>
<li class="chapter" data-level="7.3.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-creation"><i class="fa fa-check"></i><b>7.3.1</b> Vector creation</a></li>
<li class="chapter" data-level="7.3.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#fetching-vector-elements"><i class="fa fa-check"></i><b>7.3.2</b> Fetching vector elements</a></li>
<li class="chapter" data-level="7.3.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-manipulation"><i class="fa fa-check"></i><b>7.3.3</b> Vector manipulation</a></li>
<li class="chapter" data-level="7.3.4" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-arithmetic"><i class="fa fa-check"></i><b>7.3.4</b> Vector arithmetic</a></li>
<li class="chapter" data-level="7.3.5" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#matrix-1"><i class="fa fa-check"></i><b>7.3.5</b> Matrix</a></li>
<li class="chapter" data-level="7.3.6" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#data-frame-1"><i class="fa fa-check"></i><b>7.3.6</b> Data Frame</a></li>
<li class="chapter" data-level="7.3.7" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#tasks-on-iris-data-set"><i class="fa fa-check"></i><b>7.3.7</b> Tasks on Iris data set</a></li>
<li class="chapter" data-level="7.3.8" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#visualization"><i class="fa fa-check"></i><b>7.3.8</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#solutions"><i class="fa fa-check"></i><b>7.4</b> Solutions</a><ul>
<li class="chapter" data-level="7.4.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-creation-1"><i class="fa fa-check"></i><b>7.4.1</b> Vector creation</a></li>
<li class="chapter" data-level="7.4.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#fetching-vector-elements-1"><i class="fa fa-check"></i><b>7.4.2</b> Fetching vector elements</a></li>
<li class="chapter" data-level="7.4.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-manipulation-1"><i class="fa fa-check"></i><b>7.4.3</b> Vector manipulation</a></li>
<li class="chapter" data-level="7.4.4" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-arithmetic-1"><i class="fa fa-check"></i><b>7.4.4</b> Vector arithmetic</a></li>
<li class="chapter" data-level="7.4.5" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#matrix-2"><i class="fa fa-check"></i><b>7.4.5</b> Matrix</a></li>
<li class="chapter" data-level="7.4.6" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#data-frame-2"><i class="fa fa-check"></i><b>7.4.6</b> Data Frame</a></li>
<li class="chapter" data-level="7.4.7" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#tasks-on-iris-data-set-1"><i class="fa fa-check"></i><b>7.4.7</b> Tasks on iris data set</a></li>
<li class="chapter" data-level="7.4.8" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#visualization-1"><i class="fa fa-check"></i><b>7.4.8</b> Visualization</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>8</b> Descriptive statistics</a><ul>
<li class="chapter" data-level="8.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measure-of-centrality"><i class="fa fa-check"></i><b>8.1</b> Measure of Centrality</a></li>
<li class="chapter" data-level="8.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measure-of-spread"><i class="fa fa-check"></i><b>8.2</b> Measure of Spread</a></li>
<li class="chapter" data-level="8.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#handle-missing-values"><i class="fa fa-check"></i><b>8.3</b> Handle missing values</a><ul>
<li class="chapter" data-level="8.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#shape-data-distribution"><i class="fa fa-check"></i><b>8.3.1</b> Shape / Data Distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#estimate-skewness-and-kurtosis"><i class="fa fa-check"></i><b>8.4</b> Estimate Skewness and Kurtosis</a></li>
<li class="chapter" data-level="8.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#further-with-skewness-and-kurtosis."><i class="fa fa-check"></i><b>8.5</b> Further with Skewness and Kurtosis.</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="data-distributions.html"><a href="data-distributions.html"><i class="fa fa-check"></i><b>9</b> Data Distributions</a><ul>
<li class="chapter" data-level="9.1" data-path="data-distributions.html"><a href="data-distributions.html#normal-distribution"><i class="fa fa-check"></i><b>9.1</b> Normal distribution</a></li>
<li class="chapter" data-level="9.2" data-path="data-distributions.html"><a href="data-distributions.html#effect-of-mean-and-sd-parameter-on-normal-distribution"><i class="fa fa-check"></i><b>9.2</b> Effect of mean and sd parameter on normal distribution</a></li>
<li class="chapter" data-level="9.3" data-path="data-distributions.html"><a href="data-distributions.html#effect-of-n-sample-size-on-normal-distribution"><i class="fa fa-check"></i><b>9.3</b> Effect of n (sample size) on normal distribution</a></li>
<li class="chapter" data-level="9.4" data-path="data-distributions.html"><a href="data-distributions.html#use-z-score-to-calculate-percentile-area-below-or-lower-tail"><i class="fa fa-check"></i><b>9.4</b> Use z score to calculate percentile (area below or lower tail)</a></li>
<li class="chapter" data-level="9.5" data-path="data-distributions.html"><a href="data-distributions.html#use-z-score-to-calculate-upper-tail"><i class="fa fa-check"></i><b>9.5</b> Use z score to calculate Upper tail</a></li>
<li class="chapter" data-level="9.6" data-path="data-distributions.html"><a href="data-distributions.html#given-percentile-area-below-the-curve-or-lower-tail-area-find-the-z-score"><i class="fa fa-check"></i><b>9.6</b> Given percentile (area below the curve or lower tail area), find the z score</a></li>
<li class="chapter" data-level="9.7" data-path="data-distributions.html"><a href="data-distributions.html#explore-the-applet"><i class="fa fa-check"></i><b>9.7</b> Explore the applet</a></li>
<li class="chapter" data-level="9.8" data-path="data-distributions.html"><a href="data-distributions.html#evaluating-the-normal-distribution"><i class="fa fa-check"></i><b>9.8</b> Evaluating the normal distribution</a></li>
<li class="chapter" data-level="9.9" data-path="data-distributions.html"><a href="data-distributions.html#sampling-distribution"><i class="fa fa-check"></i><b>9.9</b> Sampling distribution</a></li>
<li class="chapter" data-level="9.10" data-path="data-distributions.html"><a href="data-distributions.html#standard-error"><i class="fa fa-check"></i><b>9.10</b> Standard Error</a></li>
<li class="chapter" data-level="9.11" data-path="data-distributions.html"><a href="data-distributions.html#confidence-interval"><i class="fa fa-check"></i><b>9.11</b> Confidence interval</a></li>
<li class="chapter" data-level="9.12" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-single-sample-mean"><i class="fa fa-check"></i><b>9.12</b> Hypothesis test for single sample mean</a></li>
<li class="chapter" data-level="9.13" data-path="data-distributions.html"><a href="data-distributions.html#one-tailed-test-greater"><i class="fa fa-check"></i><b>9.13</b> One tailed test (Greater)</a></li>
<li class="chapter" data-level="9.14" data-path="data-distributions.html"><a href="data-distributions.html#one-tailed-test-lesser"><i class="fa fa-check"></i><b>9.14</b> One tailed test (Lesser)</a></li>
<li class="chapter" data-level="9.15" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-two-sample-mean-unpaired"><i class="fa fa-check"></i><b>9.15</b> Hypothesis test for two sample mean, unpaired</a></li>
<li class="chapter" data-level="9.16" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-two-sample-mean-paired"><i class="fa fa-check"></i><b>9.16</b> Hypothesis test for two sample mean, paired</a></li>
<li class="chapter" data-level="9.17" data-path="data-distributions.html"><a href="data-distributions.html#check-for-normality"><i class="fa fa-check"></i><b>9.17</b> Check for normality</a></li>
<li class="chapter" data-level="9.18" data-path="data-distributions.html"><a href="data-distributions.html#check-for-uniform-variance"><i class="fa fa-check"></i><b>9.18</b> Check for uniform variance</a></li>
<li class="chapter" data-level="9.19" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-single-sample-proportion"><i class="fa fa-check"></i><b>9.19</b> Hypothesis test for single sample proportion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a><ul>
<li class="chapter" data-level="10.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>10.1</b> Simple linear Regression</a><ul>
<li class="chapter" data-level="10.1.1" data-path="regression.html"><a href="regression.html#build-model"><i class="fa fa-check"></i><b>10.1.1</b> Build model</a></li>
<li class="chapter" data-level="10.1.2" data-path="regression.html"><a href="regression.html#obtain-model-summary-linear-regression-diagnostics"><i class="fa fa-check"></i><b>10.1.2</b> Obtain model summary (Linear Regression Diagnostics)</a></li>
<li class="chapter" data-level="10.1.3" data-path="regression.html"><a href="regression.html#model-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Model coefficients</a></li>
<li class="chapter" data-level="10.1.4" data-path="regression.html"><a href="regression.html#model-significance-and-coefficient-significance"><i class="fa fa-check"></i><b>10.1.4</b> Model significance and Coefficient significance</a></li>
<li class="chapter" data-level="10.1.5" data-path="regression.html"><a href="regression.html#coefficient-of-determination-or-r-squared"><i class="fa fa-check"></i><b>10.1.5</b> Coefficient of Determination or R-squared</a></li>
<li class="chapter" data-level="10.1.6" data-path="regression.html"><a href="regression.html#standard-error-and-f-statistic"><i class="fa fa-check"></i><b>10.1.6</b> Standard Error and F-Statistic</a></li>
<li class="chapter" data-level="10.1.7" data-path="regression.html"><a href="regression.html#aic-and-bic"><i class="fa fa-check"></i><b>10.1.7</b> AIC and BIC</a></li>
<li class="chapter" data-level="10.1.8" data-path="regression.html"><a href="regression.html#residuals-and-residual-plot"><i class="fa fa-check"></i><b>10.1.8</b> Residuals and Residual plot</a></li>
<li class="chapter" data-level="10.1.9" data-path="regression.html"><a href="regression.html#how-to-know-if-the-model-is-best-fit-for-your-data"><i class="fa fa-check"></i><b>10.1.9</b> How to know if the model is best fit for your data?</a></li>
<li class="chapter" data-level="10.1.10" data-path="regression.html"><a href="regression.html#lets-predict-a-new-dataset-using-the-built-model"><i class="fa fa-check"></i><b>10.1.10</b> Lets predict a new dataset using the built model</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>10.2</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="10.2.1" data-path="regression.html"><a href="regression.html#build-multiple-regression-model"><i class="fa fa-check"></i><b>10.2.1</b> Build multiple regression model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>11</b> Clustering</a><ul>
<li class="chapter" data-level="11.1" data-path="clustering.html"><a href="clustering.html#data-preparation"><i class="fa fa-check"></i><b>11.1</b> Data preparation</a><ul>
<li class="chapter" data-level="11.1.1" data-path="clustering.html"><a href="clustering.html#load-library"><i class="fa fa-check"></i><b>11.1.1</b> Load library</a></li>
<li class="chapter" data-level="11.1.2" data-path="clustering.html"><a href="clustering.html#load-tcga-data"><i class="fa fa-check"></i><b>11.1.2</b> Load TCGA data</a></li>
<li class="chapter" data-level="11.1.3" data-path="clustering.html"><a href="clustering.html#vizualize-data"><i class="fa fa-check"></i><b>11.1.3</b> Vizualize data</a></li>
<li class="chapter" data-level="11.1.4" data-path="clustering.html"><a href="clustering.html#data-preparation-1"><i class="fa fa-check"></i><b>11.1.4</b> Data preparation</a></li>
<li class="chapter" data-level="11.1.5" data-path="clustering.html"><a href="clustering.html#check-for-na"><i class="fa fa-check"></i><b>11.1.5</b> Check for NA</a></li>
<li class="chapter" data-level="11.1.6" data-path="clustering.html"><a href="clustering.html#scale-the-data"><i class="fa fa-check"></i><b>11.1.6</b> Scale the data</a></li>
<li class="chapter" data-level="11.1.7" data-path="clustering.html"><a href="clustering.html#vizualize-data-after-scaling"><i class="fa fa-check"></i><b>11.1.7</b> Vizualize data after scaling</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>11.2</b> Clustering</a></li>
<li class="chapter" data-level="11.3" data-path="clustering.html"><a href="clustering.html#k-means-clustering"><i class="fa fa-check"></i><b>11.3</b> K-means clustering</a><ul>
<li class="chapter" data-level="11.3.1" data-path="clustering.html"><a href="clustering.html#visualizing-k-means-clusters-in-2d-space"><i class="fa fa-check"></i><b>11.3.1</b> Visualizing k-means clusters in 2D space</a></li>
<li class="chapter" data-level="11.3.2" data-path="clustering.html"><a href="clustering.html#get-details-of-clusters"><i class="fa fa-check"></i><b>11.3.2</b> Get details of clusters</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="clustering.html"><a href="clustering.html#determining-the-optimal-number-of-clusters"><i class="fa fa-check"></i><b>11.4</b> Determining The Optimal Number Of Clusters</a><ul>
<li class="chapter" data-level="11.4.1" data-path="clustering.html"><a href="clustering.html#elbow-method"><i class="fa fa-check"></i><b>11.4.1</b> Elbow method</a></li>
<li class="chapter" data-level="11.4.2" data-path="clustering.html"><a href="clustering.html#average-silhouette-method"><i class="fa fa-check"></i><b>11.4.2</b> Average silhouette method</a></li>
<li class="chapter" data-level="11.4.3" data-path="clustering.html"><a href="clustering.html#gap-statistic-method"><i class="fa fa-check"></i><b>11.4.3</b> Gap statistic method</a></li>
<li class="chapter" data-level="11.4.4" data-path="clustering.html"><a href="clustering.html#nbclust-function-30-indices-for-choosing-the-best-number-of-clusters"><i class="fa fa-check"></i><b>11.4.4</b> NbClust() function: 30 indices for choosing the best number of clusters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>12</b> PCA</a><ul>
<li class="chapter" data-level="12.1" data-path="pca.html"><a href="pca.html#about-principal-component-analysis-pca"><i class="fa fa-check"></i><b>12.1</b> About Principal Component Analysis (PCA</a></li>
<li class="chapter" data-level="12.2" data-path="pca.html"><a href="pca.html#data-preparation-2"><i class="fa fa-check"></i><b>12.2</b> Data preparation</a><ul>
<li class="chapter" data-level="12.2.1" data-path="pca.html"><a href="pca.html#load-gene-expression-data-from-tcga-breast-cancer"><i class="fa fa-check"></i><b>12.2.1</b> Load Gene expression data from TCGA Breast cancer</a></li>
<li class="chapter" data-level="12.2.2" data-path="pca.html"><a href="pca.html#data-standardization"><i class="fa fa-check"></i><b>12.2.2</b> Data standardization</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="pca.html"><a href="pca.html#perform-pca"><i class="fa fa-check"></i><b>12.3</b> Perform PCA</a></li>
<li class="chapter" data-level="12.4" data-path="pca.html"><a href="pca.html#visualization-and-interpretation"><i class="fa fa-check"></i><b>12.4</b> Visualization and Interpretation</a></li>
<li class="chapter" data-level="12.5" data-path="pca.html"><a href="pca.html#eigenvalues-variances-number-of-pcs-to-consider"><i class="fa fa-check"></i><b>12.5</b> Eigenvalues / Variances / Number of PCs to consider</a></li>
<li class="chapter" data-level="12.6" data-path="pca.html"><a href="pca.html#graph-of-variables"><i class="fa fa-check"></i><b>12.6</b> Graph of variables</a></li>
<li class="chapter" data-level="12.7" data-path="pca.html"><a href="pca.html#correlation-circle"><i class="fa fa-check"></i><b>12.7</b> Correlation circle</a></li>
<li class="chapter" data-level="12.8" data-path="pca.html"><a href="pca.html#quality-of-representation"><i class="fa fa-check"></i><b>12.8</b> Quality of representation</a></li>
<li class="chapter" data-level="12.9" data-path="pca.html"><a href="pca.html#referece"><i class="fa fa-check"></i><b>12.9</b> Referece</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="network-analysis.html"><a href="network-analysis.html"><i class="fa fa-check"></i><b>13</b> Network analysis</a><ul>
<li class="chapter" data-level="13.1" data-path="network-analysis.html"><a href="network-analysis.html#data-processing"><i class="fa fa-check"></i><b>13.1</b> Data processing</a><ul>
<li class="chapter" data-level="13.1.1" data-path="network-analysis.html"><a href="network-analysis.html#load-igraph-library"><i class="fa fa-check"></i><b>13.1.1</b> Load iGraph Library</a></li>
<li class="chapter" data-level="13.1.2" data-path="network-analysis.html"><a href="network-analysis.html#load-data"><i class="fa fa-check"></i><b>13.1.2</b> Load data</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="network-analysis.html"><a href="network-analysis.html#convert-data-frame-to-graph"><i class="fa fa-check"></i><b>13.2</b> Convert data frame to graph</a></li>
<li class="chapter" data-level="13.3" data-path="network-analysis.html"><a href="network-analysis.html#node-and-edge-details"><i class="fa fa-check"></i><b>13.3</b> Node and Edge details</a></li>
<li class="chapter" data-level="13.4" data-path="network-analysis.html"><a href="network-analysis.html#plot-parameters"><i class="fa fa-check"></i><b>13.4</b> Plot Parameters</a></li>
<li class="chapter" data-level="13.5" data-path="network-analysis.html"><a href="network-analysis.html#network-layouts"><i class="fa fa-check"></i><b>13.5</b> Network layouts</a></li>
<li class="chapter" data-level="13.6" data-path="network-analysis.html"><a href="network-analysis.html#network-and-node-descriptives"><i class="fa fa-check"></i><b>13.6</b> Network and node descriptives</a><ul>
<li class="chapter" data-level="13.6.1" data-path="network-analysis.html"><a href="network-analysis.html#edge-density"><i class="fa fa-check"></i><b>13.6.1</b> Edge density</a></li>
<li class="chapter" data-level="13.6.2" data-path="network-analysis.html"><a href="network-analysis.html#diameter"><i class="fa fa-check"></i><b>13.6.2</b> Diameter</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="network-analysis.html"><a href="network-analysis.html#centrality-centralization"><i class="fa fa-check"></i><b>13.7</b> Centrality &amp; centralization</a><ul>
<li class="chapter" data-level="13.7.1" data-path="network-analysis.html"><a href="network-analysis.html#degree-centrality"><i class="fa fa-check"></i><b>13.7.1</b> Degree centrality</a></li>
<li class="chapter" data-level="13.7.2" data-path="network-analysis.html"><a href="network-analysis.html#closeness"><i class="fa fa-check"></i><b>13.7.2</b> Closeness</a></li>
<li class="chapter" data-level="13.7.3" data-path="network-analysis.html"><a href="network-analysis.html#betweenness"><i class="fa fa-check"></i><b>13.7.3</b> Betweenness</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="network-analysis.html"><a href="network-analysis.html#hubs-and-authorities"><i class="fa fa-check"></i><b>13.8</b> Hubs and authorities</a></li>
<li class="chapter" data-level="13.9" data-path="network-analysis.html"><a href="network-analysis.html#distances-and-paths"><i class="fa fa-check"></i><b>13.9</b> Distances and paths</a></li>
<li class="chapter" data-level="13.10" data-path="network-analysis.html"><a href="network-analysis.html#cliques"><i class="fa fa-check"></i><b>13.10</b> Cliques</a></li>
<li class="chapter" data-level="13.11" data-path="network-analysis.html"><a href="network-analysis.html#community-detection"><i class="fa fa-check"></i><b>13.11</b> Community detection</a></li>
<li class="chapter" data-level="13.12" data-path="network-analysis.html"><a href="network-analysis.html#interative-network"><i class="fa fa-check"></i><b>13.12</b> Interative network</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Visit site</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BioSakshat - Free Study Materials</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="pca" class="section level1">
<h1><span class="header-section-number">Chapter 12</span> PCA</h1>
<div id="about-principal-component-analysis-pca" class="section level2">
<h2><span class="header-section-number">12.1</span> About Principal Component Analysis (PCA</h2>
<p>The central idea of principal component analysis (PCA) is to <strong>reduce the dimensionality</strong> of a data set consisting of a large number of <strong>interrelated variables</strong>, while retaining as much as possible of the variation present in the data set. This is achieved by <strong>transforming to a new set of variables</strong>, the principal components (PCs), which are <strong>uncorrelated</strong>
ordered so that the first few retain most of the variation present in all of the original variables.</p>
<p>To begin with PCA analysis our data must be in 2 dimensional form (data frame or matrix) where individuals or observations are represented in rows while variables or features are represented in columns. It is important to note that for PCA to work well, there must be some degree of correlation among variables. In that case PCA will try to detect such correlated variables and reduce the dimension by giving you new set of variables that are not correlated to each other. These new variables correspond to a linear combination of the originals. In simple term, PCA reduces the dimesnion by identifying correlated variables and giving you a new set of uncorrelated variables (Princical components).</p>
<p><strong>PCA method is particularly useful when the variables within the data set are highly correlated</strong></p>
<p>Lets begin with analysis by taking gene expression dataset from TCGA dataset for breast cancer.</p>
</div>
<div id="data-preparation-2" class="section level2">
<h2><span class="header-section-number">12.2</span> Data preparation</h2>
<div class="sourceCode" id="cb1052"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1052-1" data-line-number="1"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb1052-2" data-line-number="2"><span class="kw">library</span>(data.table)</a>
<a class="sourceLine" id="cb1052-3" data-line-number="3"><span class="kw">library</span>(<span class="st">&quot;factoextra&quot;</span>)</a></code></pre></div>
<div id="load-gene-expression-data-from-tcga-breast-cancer" class="section level3">
<h3><span class="header-section-number">12.2.1</span> Load Gene expression data from TCGA Breast cancer</h3>
<div class="sourceCode" id="cb1053"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1053-1" data-line-number="1">df =<span class="st"> </span><span class="kw">fread</span>(<span class="st">&quot;./data/stat/BRCA_TCGA_exp.tsv&quot;</span>, <span class="dt">header=</span>T) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">data.frame</span>()</a>
<a class="sourceLine" id="cb1053-2" data-line-number="2"><span class="kw">dim</span>(df);</a></code></pre></div>
<pre><code>## [1] 413  49</code></pre>
<div class="sourceCode" id="cb1055"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1055-1" data-line-number="1"><span class="co"># Genes in columns and samples in rows</span></a>
<a class="sourceLine" id="cb1055-2" data-line-number="2"><span class="kw">print</span>(df[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]);</a></code></pre></div>
<pre><code>##            Sample   UBE2T   BIRC5    NUF2    CDC6
## 1 TCGA-5T-A9QA-01  1.9323  0.2744  1.7735  1.3728
## 2 TCGA-A1-A0SE-01  0.7931 -0.1335 -0.0023 -0.1102
## 3 TCGA-A1-A0SH-01 -0.6785 -0.4435 -0.9456 -0.7541</code></pre>
<div class="sourceCode" id="cb1057"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1057-1" data-line-number="1"><span class="kw">rownames</span>(df) =<span class="st"> </span>df<span class="op">$</span>Sample;</a>
<a class="sourceLine" id="cb1057-2" data-line-number="2">df<span class="op">$</span>Sample =<span class="st"> </span><span class="ot">NULL</span>;</a>
<a class="sourceLine" id="cb1057-3" data-line-number="3"><span class="kw">dim</span>(df);</a></code></pre></div>
<pre><code>## [1] 413  48</code></pre>
<div class="sourceCode" id="cb1059"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1059-1" data-line-number="1"><span class="kw">print</span>(df[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]);</a></code></pre></div>
<pre><code>##                   UBE2T   BIRC5    NUF2    CDC6   CCNB1
## TCGA-5T-A9QA-01  1.9323  0.2744  1.7735  1.3728  0.1060
## TCGA-A1-A0SE-01  0.7931 -0.1335 -0.0023 -0.1102  0.1857
## TCGA-A1-A0SH-01 -0.6785 -0.4435 -0.9456 -0.7541 -0.8197</code></pre>
</div>
<div id="data-standardization" class="section level3">
<h3><span class="header-section-number">12.2.2</span> Data standardization</h3>
<p>In principal component analysis, variables are often scaled (i.e. standardized). This is particularly recommended when variables are measured in different scales (e.g: kilograms, kilometers, centimeters, …); otherwise, the PCA outputs obtained will be severely affected.</p>
<p>The goal is to make the variables comparable. Generally variables are scaled to have i) standard deviation one and ii) mean zero.</p>
<p>The standardization of data is an approach widely used in the context of gene expression data analysis before PCA and clustering analysis. We might also want to scale the data when the mean and/or the standard deviation of variables are largely different.</p>
<p>When scaling variables, the data can be transformed as follow:</p>
<p>xi−mean(x)/sd(x)</p>
<p>Where mean(x) is the mean of x values, and sd(x) is the standard deviation (SD).</p>
<p>The R base function scale() can be used to standardize the data. It takes a numeric matrix as an input and performs the scaling on the columns.</p>
<p>Note that, by default, the function PCA() [in FactoMineR], standardizes the data automatically during the PCA; so you don’t need do this transformation before the PCA.</p>
</div>
</div>
<div id="perform-pca" class="section level2">
<h2><span class="header-section-number">12.3</span> Perform PCA</h2>
<div class="sourceCode" id="cb1061"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1061-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;FactoMineR&quot;</span>)</a>
<a class="sourceLine" id="cb1061-2" data-line-number="2">res.pca &lt;-<span class="st"> </span><span class="kw">PCA</span>(df, <span class="dt">graph =</span> <span class="ot">FALSE</span>);</a>
<a class="sourceLine" id="cb1061-3" data-line-number="3"><span class="kw">print</span>(res.pca);</a></code></pre></div>
<pre><code>## **Results for the Principal Component Analysis (PCA)**
## The analysis was performed on 413 individuals, described by 48 variables
## *The results are available in the following objects:
## 
##    name               description                          
## 1  &quot;$eig&quot;             &quot;eigenvalues&quot;                        
## 2  &quot;$var&quot;             &quot;results for the variables&quot;          
## 3  &quot;$var$coord&quot;       &quot;coord. for the variables&quot;           
## 4  &quot;$var$cor&quot;         &quot;correlations variables - dimensions&quot;
## 5  &quot;$var$cos2&quot;        &quot;cos2 for the variables&quot;             
## 6  &quot;$var$contrib&quot;     &quot;contributions of the variables&quot;     
## 7  &quot;$ind&quot;             &quot;results for the individuals&quot;        
## 8  &quot;$ind$coord&quot;       &quot;coord. for the individuals&quot;         
## 9  &quot;$ind$cos2&quot;        &quot;cos2 for the individuals&quot;           
## 10 &quot;$ind$contrib&quot;     &quot;contributions of the individuals&quot;   
## 11 &quot;$call&quot;            &quot;summary statistics&quot;                 
## 12 &quot;$call$centre&quot;     &quot;mean of the variables&quot;              
## 13 &quot;$call$ecart.type&quot; &quot;standard error of the variables&quot;    
## 14 &quot;$call$row.w&quot;      &quot;weights for the individuals&quot;        
## 15 &quot;$call$col.w&quot;      &quot;weights for the variables&quot;</code></pre>
</div>
<div id="visualization-and-interpretation" class="section level2">
<h2><span class="header-section-number">12.4</span> Visualization and Interpretation</h2>
<p>We’ll use the factoextra R package to help in the interpretation of PCA. No matter what function you decide to use [stats::prcomp(), FactoMiner::PCA(), ade4::dudi.pca(), ExPosition::epPCA()], you can easily extract and visualize the results of PCA using R functions provided in the factoextra R package.</p>
<p>These functions include:</p>
<ul>
<li>get_eigenvalue(res.pca): Extract the eigenvalues/variances of principal components</li>
<li>fviz_eig(res.pca): Visualize the eigenvalues</li>
<li>get_pca_ind(res.pca), get_pca_var(res.pca): Extract the results for individuals and variables, respectively.</li>
<li>fviz_pca_ind(res.pca), fviz_pca_var(res.pca): Visualize the results individuals and variables, respectively.</li>
<li>fviz_pca_biplot(res.pca): Make a biplot of individuals and variables.</li>
</ul>
</div>
<div id="eigenvalues-variances-number-of-pcs-to-consider" class="section level2">
<h2><span class="header-section-number">12.5</span> Eigenvalues / Variances / Number of PCs to consider</h2>
<div class="sourceCode" id="cb1063"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1063-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;factoextra&quot;</span>)</a>
<a class="sourceLine" id="cb1063-2" data-line-number="2">eig.val &lt;-<span class="st"> </span><span class="kw">get_eigenvalue</span>(res.pca)</a>
<a class="sourceLine" id="cb1063-3" data-line-number="3">eig.val</a></code></pre></div>
<pre><code>##         eigenvalue variance.percent cumulative.variance.percent
## Dim.1  14.14791842       29.4748300                    29.47483
## Dim.2   3.94971231        8.2285673                    37.70340
## Dim.3   3.14962824        6.5617255                    44.26512
## Dim.4   1.94797974        4.0582911                    48.32341
## Dim.5   1.72929760        3.6027033                    51.92612
## Dim.6   1.44630087        3.0131268                    54.93924
## Dim.7   1.39375810        2.9036627                    57.84291
## Dim.8   1.23543483        2.5738226                    60.41673
## Dim.9   1.18112455        2.4606761                    62.87741
## Dim.10  1.14208359        2.3793408                    65.25675
## Dim.11  1.04262060        2.1721263                    67.42887
## Dim.12  0.96778667        2.0162222                    69.44509
## Dim.13  0.89097953        1.8562074                    71.30130
## Dim.14  0.84246903        1.7551438                    73.05645
## Dim.15  0.82614443        1.7211342                    74.77758
## Dim.16  0.77973076        1.6244391                    76.40202
## Dim.17  0.74045143        1.5426071                    77.94463
## Dim.18  0.69874753        1.4557240                    79.40035
## Dim.19  0.64832720        1.3506817                    80.75103
## Dim.20  0.62876820        1.3099337                    82.06097
## Dim.21  0.59805408        1.2459460                    83.30691
## Dim.22  0.56207691        1.1709936                    84.47791
## Dim.23  0.55446717        1.1551399                    85.63305
## Dim.24  0.54943762        1.1446617                    86.77771
## Dim.25  0.50047278        1.0426516                    87.82036
## Dim.26  0.46999305        0.9791522                    88.79951
## Dim.27  0.44726751        0.9318073                    89.73132
## Dim.28  0.44451805        0.9260793                    90.65740
## Dim.29  0.41449796        0.8635374                    91.52093
## Dim.30  0.38835714        0.8090774                    92.33001
## Dim.31  0.37813713        0.7877857                    93.11780
## Dim.32  0.34982619        0.7288046                    93.84660
## Dim.33  0.33271124        0.6931484                    94.53975
## Dim.34  0.30820183        0.6420872                    95.18184
## Dim.35  0.28832408        0.6006752                    95.78251
## Dim.36  0.26472387        0.5515081                    96.33402
## Dim.37  0.23075267        0.4807347                    96.81476
## Dim.38  0.22028177        0.4589204                    97.27368
## Dim.39  0.20299552        0.4229073                    97.69658
## Dim.40  0.18797839        0.3916216                    98.08821
## Dim.41  0.16527540        0.3443237                    98.43253
## Dim.42  0.14317163        0.2982742                    98.73080
## Dim.43  0.14014861        0.2919763                    99.02278
## Dim.44  0.11948342        0.2489238                    99.27170
## Dim.45  0.11157799        0.2324541                    99.50416
## Dim.46  0.09824474        0.2046765                    99.70883
## Dim.47  0.08201146        0.1708572                    99.87969
## Dim.48  0.05774817        0.1203087                   100.00000</code></pre>
<p>PC1 explains 29.47% variation in the data while PC2 explains 8.22% variation. Together they explain 37.70% of variation</p>
<p>Eigenvalues can be used to determine the number of principal components to retain after PCA</p>
<ul>
<li>An eigenvalue &gt; 1 indicates that PCs account for more variance than accounted by one of the original variables in standardized data. This is commonly used as a cutoff point for which PCs are retained. This holds true only when the data are standardized.</li>
<li>You can also limit the number of component to that number that accounts for a certain fraction of the total variance. For example, if you are satisfied with 70% of the total variance explained then use the number of components to achieve that.</li>
</ul>
<p>Unfortunately, there is no well-accepted objective way to decide how many principal components are enough. This will depend on the specific field of application and the specific data set. In practice, we tend to look at the first few principal components in order to find interesting patterns in the data.</p>
<p>An alternative method to determine the number of principal components is to look at a <strong>Scree Plot</strong>, which is the plot of eigenvalues ordered from largest to the smallest. The number of component is determined at the point, beyond which the remaining eigenvalues are all relatively small and of comparable size (Jollife 2002, Peres-Neto, Jackson, and Somers (2005)).</p>
<p>The scree plot can be produced using the function fviz_eig() or fviz_screeplot() [factoextra package].</p>
<div class="sourceCode" id="cb1065"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1065-1" data-line-number="1"><span class="kw">fviz_eig</span>(res.pca, <span class="dt">addlabels =</span> <span class="ot">TRUE</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">40</span>))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-275-1.png" width="672" /></p>
</div>
<div id="graph-of-variables" class="section level2">
<h2><span class="header-section-number">12.6</span> Graph of variables</h2>
<p>A simple method to extract the results, for variables, from a PCA output is to use the function get_pca_var() [factoextra package]. This function provides a list of matrices containing all the results for the active variables (coordinates, correlation between variables and axes, squared cosine and contributions)</p>
<div class="sourceCode" id="cb1066"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1066-1" data-line-number="1">var &lt;-<span class="st"> </span><span class="kw">get_pca_var</span>(res.pca)</a>
<a class="sourceLine" id="cb1066-2" data-line-number="2">var</a></code></pre></div>
<pre><code>## Principal Component Analysis Results for variables
##  ===================================================
##   Name       Description                                    
## 1 &quot;$coord&quot;   &quot;Coordinates for the variables&quot;                
## 2 &quot;$cor&quot;     &quot;Correlations between variables and dimensions&quot;
## 3 &quot;$cos2&quot;    &quot;Cos2 for the variables&quot;                       
## 4 &quot;$contrib&quot; &quot;contributions of the variables&quot;</code></pre>
<p>The components of the get_pca_var() can be used in the plot of variables as follow:</p>
<ul>
<li>var$coord: coordinates of variables to create a scatter plot</li>
<li>var$cos2: represents the quality of representation for variables on the factor map. It’s calculated as the squared coordinates: var.cos2 = var.coord * var.coord.</li>
<li>var$contrib: contains the contributions (in percentage) of the variables to the principal components. The contribution of a variable (var) to a given principal component is (in percentage) : (var.cos2 * 100) / (total cos2 of the component).</li>
</ul>
<p>We can plot variables on factor map using var<span class="math inline">\(coord and colour them using either var\)</span>cos2(Quality) or var$contrib (contribution)</p>
<div class="sourceCode" id="cb1068"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1068-1" data-line-number="1"><span class="co"># Coordinates</span></a>
<a class="sourceLine" id="cb1068-2" data-line-number="2"><span class="kw">head</span>(var<span class="op">$</span>coord)</a></code></pre></div>
<pre><code>##           Dim.1     Dim.2       Dim.3         Dim.4       Dim.5
## UBE2T 0.7253340 0.2277836  0.05089143  0.1303429090 -0.02312285
## BIRC5 0.7207480 0.1672497  0.06828535  0.3021446496 -0.22747635
## NUF2  0.6668279 0.1828370  0.18492054  0.0002209955  0.08668259
## CDC6  0.3065962 0.3628674 -0.42996927 -0.0201999332  0.27329481
## CCNB1 0.7365610 0.3673432  0.05506443  0.2036965058  0.08426123
## TYMS  0.6756032 0.1873181  0.15157941 -0.0439218609 -0.05554614</code></pre>
<div class="sourceCode" id="cb1070"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1070-1" data-line-number="1"><span class="co"># Cos2: quality on the factore map</span></a>
<a class="sourceLine" id="cb1070-2" data-line-number="2"><span class="kw">head</span>(var<span class="op">$</span>cos2)</a></code></pre></div>
<pre><code>##            Dim.1      Dim.2       Dim.3        Dim.4        Dim.5
## UBE2T 0.52610945 0.05188535 0.002589938 1.698927e-02 0.0005346662
## BIRC5 0.51947763 0.02797247 0.004662889 9.129139e-02 0.0517454883
## NUF2  0.44465946 0.03342935 0.034195607 4.883902e-08 0.0075138715
## CDC6  0.09400125 0.13167275 0.184873574 4.080373e-04 0.0746900536
## CCNB1 0.54252209 0.13494102 0.003032091 4.149227e-02 0.0070999541
## TYMS  0.45643969 0.03508808 0.022976319 1.929130e-03 0.0030853732</code></pre>
<div class="sourceCode" id="cb1072"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1072-1" data-line-number="1"><span class="co"># Contributions to the principal components</span></a>
<a class="sourceLine" id="cb1072-2" data-line-number="2"><span class="kw">head</span>(var<span class="op">$</span>contrib)</a></code></pre></div>
<pre><code>##           Dim.1     Dim.2      Dim.3        Dim.4      Dim.5
## UBE2T 3.7186350 1.3136487 0.08222996 8.721484e-01 0.03091811
## BIRC5 3.6717602 0.7082153 0.14804569 4.686465e+00 2.99228359
## NUF2  3.1429320 0.8463743 1.08570296 2.507162e-06 0.43450425
## CDC6  0.6644176 3.3337302 5.86969509 2.094669e-02 4.31909774
## CCNB1 3.8346425 3.4164771 0.09626822 2.130015e+00 0.41056866
## TYMS  3.2261968 0.8883706 0.72949304 9.903234e-02 0.17841771</code></pre>
<p>Lets plot variables</p>
</div>
<div id="correlation-circle" class="section level2">
<h2><span class="header-section-number">12.7</span> Correlation circle</h2>
<div class="sourceCode" id="cb1074"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1074-1" data-line-number="1"><span class="kw">head</span>(var<span class="op">$</span>coord, <span class="dv">4</span>)</a></code></pre></div>
<pre><code>##           Dim.1     Dim.2       Dim.3         Dim.4       Dim.5
## UBE2T 0.7253340 0.2277836  0.05089143  0.1303429090 -0.02312285
## BIRC5 0.7207480 0.1672497  0.06828535  0.3021446496 -0.22747635
## NUF2  0.6668279 0.1828370  0.18492054  0.0002209955  0.08668259
## CDC6  0.3065962 0.3628674 -0.42996927 -0.0201999332  0.27329481</code></pre>
<div class="sourceCode" id="cb1076"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1076-1" data-line-number="1"><span class="co"># To plot variables, type this:</span></a>
<a class="sourceLine" id="cb1076-2" data-line-number="2"><span class="kw">fviz_pca_var</span>(res.pca, <span class="dt">col.var =</span> <span class="st">&quot;black&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-278-1.png" width="672" />
The plot above is also known as variable correlation plots. It shows the relationships between all variables. It can be interpreted as follow:</p>
<ul>
<li>Positively correlated variables are grouped together.</li>
<li>Negatively correlated variables are positioned on opposite sides of the plot origin (opposed quadrants).</li>
<li>The distance between variables and the origin measures the quality of the variables on the factor map. Variables that are away from the origin are well represented on the factor map.</li>
</ul>
</div>
<div id="quality-of-representation" class="section level2">
<h2><span class="header-section-number">12.8</span> Quality of representation</h2>
<p>The quality of representation of the variables on factor map is called cos2 (square cosine, squared coordinates) . You can access to the cos2 as follow:</p>
<div class="sourceCode" id="cb1077"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1077-1" data-line-number="1"><span class="kw">head</span>(var<span class="op">$</span>cos2, <span class="dv">4</span>)</a></code></pre></div>
<pre><code>##            Dim.1      Dim.2       Dim.3        Dim.4        Dim.5
## UBE2T 0.52610945 0.05188535 0.002589938 1.698927e-02 0.0005346662
## BIRC5 0.51947763 0.02797247 0.004662889 9.129139e-02 0.0517454883
## NUF2  0.44465946 0.03342935 0.034195607 4.883902e-08 0.0075138715
## CDC6  0.09400125 0.13167275 0.184873574 4.080373e-04 0.0746900536</code></pre>
<p>You can visualize the cos2 of variables on all the dimensions using the corrplot package:</p>
<div class="sourceCode" id="cb1079"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1079-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;corrplot&quot;</span>)</a></code></pre></div>
<pre><code>## corrplot 0.84 loaded</code></pre>
<div class="sourceCode" id="cb1081"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1081-1" data-line-number="1"><span class="kw">corrplot</span>(<span class="kw">t</span>(var<span class="op">$</span>cos2), <span class="dt">is.corr=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-280-1.png" width="672" /></p>
<p>It’s also possible to create a bar plot of variables cos2 using the function fviz_cos2()[in factoextra]:</p>
<div class="sourceCode" id="cb1082"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1082-1" data-line-number="1"><span class="co"># Total cos2 of variables on Dim.1 and Dim.2</span></a>
<a class="sourceLine" id="cb1082-2" data-line-number="2"><span class="kw">fviz_cos2</span>(res.pca, <span class="dt">choice =</span> <span class="st">&quot;var&quot;</span>, <span class="dt">axes =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-281-1.png" width="672" /></p>
<p>Note that,</p>
<ul>
<li>A high cos2 indicates a good representation of the variable on the principal component. In this case the variable is positioned close to the circumference of the correlation circle.</li>
<li>A low cos2 indicates that the variable is not perfectly represented by the PCs. In this case the variable is close to the center of the circle.</li>
</ul>
<p>For a given variable, the sum of the cos2 on all the principal components is equal to one.</p>
<ul>
<li>The cos2 values are used to estimate the quality of the representation</li>
<li>The closer a variable is to the circle of correlations, the better its representation on the factor map (and the more important it is to interpret these components)</li>
<li>Variables that are closed to the center of the plot are less important for the first components.</li>
</ul>
<p>It’s possible to color variables by their cos2 values using the argument col.var = “cos2”. This produces a gradient colors. In this case, the argument gradient.cols can be used to provide a custom color. For instance, gradient.cols = c(“white”, “blue”, “red”) means that:</p>
<ul>
<li>variables with low cos2 values will be colored in “white”</li>
<li>variables with mid cos2 values will be colored in “blue”</li>
<li>variables with high cos2 values will be colored in red</li>
</ul>
<div class="sourceCode" id="cb1083"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1083-1" data-line-number="1"><span class="co"># Color by cos2 values: quality on the factor map</span></a>
<a class="sourceLine" id="cb1083-2" data-line-number="2"><span class="kw">fviz_pca_var</span>(res.pca, <span class="dt">col.var =</span> <span class="st">&quot;cos2&quot;</span>,</a>
<a class="sourceLine" id="cb1083-3" data-line-number="3">             <span class="dt">gradient.cols =</span> <span class="kw">c</span>(<span class="st">&quot;#00AFBB&quot;</span>, <span class="st">&quot;#E7B800&quot;</span>, <span class="st">&quot;#FC4E07&quot;</span>), </a>
<a class="sourceLine" id="cb1083-4" data-line-number="4">             <span class="dt">repel =</span> <span class="ot">TRUE</span> <span class="co"># Avoid text overlapping</span></a>
<a class="sourceLine" id="cb1083-5" data-line-number="5">             )</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-282-1.png" width="672" /></p>
</div>
<div id="referece" class="section level2">
<h2><span class="header-section-number">12.9</span> Referece</h2>
<ol style="list-style-type: decimal">
<li>Jollife, I.T. 2002. Principal Component Analysis. 2nd ed. New York: Springer-Verlag. <a href="https://goo.gl/SB86SR" class="uri">https://goo.gl/SB86SR</a>.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="clustering.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="network-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
