<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145318313-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-145318313-2');
</script>


<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-3848514720264642",
          enable_page_level_ads: true
     });
</script>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Regression | BioSakshat - Free Study Materials</title>
  <meta name="description" content="+++" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Regression | BioSakshat - Free Study Materials" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="+++" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Regression | BioSakshat - Free Study Materials" />
  
  <meta name="twitter:description" content="+++" />
  

<meta name="author" content="By Priyabrata Panigrahi and Pandurang Kolekar" />


<meta name="date" content="2019-08-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-distributions.html">
<link rel="next" href="clustering.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/vis-4.20.1/vis.css" rel="stylesheet" />
<script src="libs/vis-4.20.1/vis.min.js"></script>
<script src="libs/visNetwork-binding-2.0.7/visNetwork.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BioSakshat</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Site navigation</a></li>
<li class="chapter" data-level="2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html"><i class="fa fa-check"></i><b>2</b> Data types and Data structures</a><ul>
<li class="chapter" data-level="2.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#lets-begin"><i class="fa fa-check"></i><b>2.1</b> Lets Begin</a></li>
<li class="chapter" data-level="2.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#expression"><i class="fa fa-check"></i><b>2.2</b> Expression</a></li>
<li class="chapter" data-level="2.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#assignment"><i class="fa fa-check"></i><b>2.3</b> Assignment</a></li>
<li class="chapter" data-level="2.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#working-directory"><i class="fa fa-check"></i><b>2.4</b> Working directory</a></li>
<li class="chapter" data-level="2.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#list-of-objects-in-workspaceenvironment"><i class="fa fa-check"></i><b>2.5</b> List of objects in workspace/environment</a></li>
<li class="chapter" data-level="2.6" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#getting-help-in-r"><i class="fa fa-check"></i><b>2.6</b> getting help in R</a><ul>
<li class="chapter" data-level="2.6.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#some-things-to-remember"><i class="fa fa-check"></i><b>2.6.1</b> Some things to Remember</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#data-types"><i class="fa fa-check"></i><b>2.7</b> Data Types</a></li>
<li class="chapter" data-level="2.8" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#data-structures"><i class="fa fa-check"></i><b>2.8</b> Data Structures</a></li>
<li class="chapter" data-level="2.9" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#vector"><i class="fa fa-check"></i><b>2.9</b> Vector</a><ul>
<li class="chapter" data-level="2.9.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#creating-a-vector"><i class="fa fa-check"></i><b>2.9.1</b> Creating a vector</a></li>
<li class="chapter" data-level="2.9.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-vector-of-one-element"><i class="fa fa-check"></i><b>2.9.2</b> Create Vector of one element</a></li>
<li class="chapter" data-level="2.9.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-vector-using-range-operator"><i class="fa fa-check"></i><b>2.9.3</b> Create Vector using Range operator (:)</a></li>
<li class="chapter" data-level="2.9.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-vector-using-c"><i class="fa fa-check"></i><b>2.9.4</b> Create Vector using c()</a></li>
<li class="chapter" data-level="2.9.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#seq-function"><i class="fa fa-check"></i><b>2.9.5</b> seq() function</a></li>
<li class="chapter" data-level="2.9.6" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#rep-function"><i class="fa fa-check"></i><b>2.9.6</b> rep() function</a></li>
<li class="chapter" data-level="2.9.7" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#sample-function"><i class="fa fa-check"></i><b>2.9.7</b> sample() function</a></li>
<li class="chapter" data-level="2.9.8" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#rnorm-function"><i class="fa fa-check"></i><b>2.9.8</b> rnorm() function</a></li>
<li class="chapter" data-level="2.9.9" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetching-elements-from-a-vector"><i class="fa fa-check"></i><b>2.9.9</b> Fetching elements from a vector</a></li>
<li class="chapter" data-level="2.9.10" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#delete-elements-from-a-vector"><i class="fa fa-check"></i><b>2.9.10</b> Delete element(s) from a vector</a></li>
<li class="chapter" data-level="2.9.11" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#add-elements-to-existing-vector"><i class="fa fa-check"></i><b>2.9.11</b> Add element(s) to existing vector</a></li>
<li class="chapter" data-level="2.9.12" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#replace-elements-in-existing-vector"><i class="fa fa-check"></i><b>2.9.12</b> Replace elements in existing vector</a></li>
<li class="chapter" data-level="2.9.13" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#inbuilt-functions-for-numeric-vector"><i class="fa fa-check"></i><b>2.9.13</b> Inbuilt functions for numeric vector</a></li>
<li class="chapter" data-level="2.9.14" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#correlation-using-cor"><i class="fa fa-check"></i><b>2.9.14</b> Correlation using cor()</a></li>
<li class="chapter" data-level="2.9.15" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#set-operations"><i class="fa fa-check"></i><b>2.9.15</b> Set operations</a></li>
<li class="chapter" data-level="2.9.16" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#arithmetic-expressions"><i class="fa fa-check"></i><b>2.9.16</b> Arithmetic expressions</a></li>
<li class="chapter" data-level="2.9.17" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#arithmetic-operations-on-vector"><i class="fa fa-check"></i><b>2.9.17</b> Arithmetic operations on vector</a></li>
<li class="chapter" data-level="2.9.18" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#operator-precedence"><i class="fa fa-check"></i><b>2.9.18</b> Operator precedence</a></li>
<li class="chapter" data-level="2.9.19" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#conditional-statements"><i class="fa fa-check"></i><b>2.9.19</b> Conditional statements</a></li>
<li class="chapter" data-level="2.9.20" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-for-missing-values"><i class="fa fa-check"></i><b>2.9.20</b> Check for missing values</a></li>
<li class="chapter" data-level="2.9.21" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-data-types-and-data-structures"><i class="fa fa-check"></i><b>2.9.21</b> Check data types and data structures</a></li>
<li class="chapter" data-level="2.9.22" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#implicit-data-type-conversion"><i class="fa fa-check"></i><b>2.9.22</b> Implicit Data type conversion</a></li>
<li class="chapter" data-level="2.9.23" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#character-vector-and-related-functions"><i class="fa fa-check"></i><b>2.9.23</b> Character vector and related functions</a></li>
<li class="chapter" data-level="2.9.24" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#explicit-data-type-conversion"><i class="fa fa-check"></i><b>2.9.24</b> Explicit Data Type Conversion</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#matrix"><i class="fa fa-check"></i><b>2.10</b> Matrix</a><ul>
<li class="chapter" data-level="2.10.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-a-matrix-from-vector-using-dim-attributes"><i class="fa fa-check"></i><b>2.10.1</b> Create a matrix from vector using dim attributes</a></li>
<li class="chapter" data-level="2.10.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-matrix-using-matrix"><i class="fa fa-check"></i><b>2.10.2</b> Create matrix using matrix()</a></li>
<li class="chapter" data-level="2.10.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#functions-that-can-be-applied-to-a-matrix"><i class="fa fa-check"></i><b>2.10.3</b> Functions that can be applied to a matrix</a></li>
<li class="chapter" data-level="2.10.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#assign-columnrow-names"><i class="fa fa-check"></i><b>2.10.4</b> Assign column/row names</a></li>
<li class="chapter" data-level="2.10.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-elements-from-a-matrix-using-indices"><i class="fa fa-check"></i><b>2.10.5</b> Fetch elements from a matrix using indices</a></li>
<li class="chapter" data-level="2.10.6" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-element-using-index-matrix"><i class="fa fa-check"></i><b>2.10.6</b> Fetch element using index matrix</a></li>
<li class="chapter" data-level="2.10.7" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-elements-from-a-matrix-using-row-and-column-names"><i class="fa fa-check"></i><b>2.10.7</b> Fetch elements from a matrix using row and column names</a></li>
<li class="chapter" data-level="2.10.8" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#insert-rows-and-columns-by-rbind-and-cbind"><i class="fa fa-check"></i><b>2.10.8</b> Insert rows and columns by rbind() and cbind()</a></li>
<li class="chapter" data-level="2.10.9" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-matrix-using-rbind-and-cbind"><i class="fa fa-check"></i><b>2.10.9</b> Create matrix using rbind() and cbind()</a></li>
<li class="chapter" data-level="2.10.10" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#delete-rows-and-columns"><i class="fa fa-check"></i><b>2.10.10</b> Delete row(s) and column(s)</a></li>
<li class="chapter" data-level="2.10.11" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-for-matrix"><i class="fa fa-check"></i><b>2.10.11</b> Check for matrix</a></li>
<li class="chapter" data-level="2.10.12" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#conditional-statements-on-matrix"><i class="fa fa-check"></i><b>2.10.12</b> Conditional statements on matrix</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#data-frame"><i class="fa fa-check"></i><b>2.11</b> Data Frame</a><ul>
<li class="chapter" data-level="2.11.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#create-a-data-frame"><i class="fa fa-check"></i><b>2.11.1</b> Create a data frame</a></li>
<li class="chapter" data-level="2.11.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#fetch-values-from-a-data-frame"><i class="fa fa-check"></i><b>2.11.2</b> Fetch values from a data frame</a></li>
<li class="chapter" data-level="2.11.3" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#insert-column-to-data-frame"><i class="fa fa-check"></i><b>2.11.3</b> Insert column to data frame</a></li>
<li class="chapter" data-level="2.11.4" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#delete-column-or-row-from-data-frame"><i class="fa fa-check"></i><b>2.11.4</b> Delete column or row from data frame</a></li>
<li class="chapter" data-level="2.11.5" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#check-for-data-frame"><i class="fa fa-check"></i><b>2.11.5</b> Check for data frame</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#list"><i class="fa fa-check"></i><b>2.12</b> List</a><ul>
<li class="chapter" data-level="2.12.1" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#access-component-of-list-using-notation"><i class="fa fa-check"></i><b>2.12.1</b> Access component of list using $ notation</a></li>
<li class="chapter" data-level="2.12.2" data-path="data-types-and-data-structures.html"><a href="data-types-and-data-structures.html#access-component-of-list-using"><i class="fa fa-check"></i><b>2.12.2</b> Access component of list using []</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html"><i class="fa fa-check"></i><b>3</b> If/For/Function/IO</a><ul>
<li class="chapter" data-level="3.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#conditional-statements-1"><i class="fa fa-check"></i><b>3.1</b> Conditional statements</a></li>
<li class="chapter" data-level="3.2" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#repetitive-execution-using-for-loop"><i class="fa fa-check"></i><b>3.2</b> Repetitive execution using for loop</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#task"><i class="fa fa-check"></i><b>3.2.1</b> Task</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#functions"><i class="fa fa-check"></i><b>3.3</b> Functions</a><ul>
<li class="chapter" data-level="3.3.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#define-function"><i class="fa fa-check"></i><b>3.3.1</b> Define function</a></li>
<li class="chapter" data-level="3.3.2" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#call-function"><i class="fa fa-check"></i><b>3.3.2</b> Call function</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#file-io"><i class="fa fa-check"></i><b>3.4</b> File IO</a><ul>
<li class="chapter" data-level="3.4.1" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#the-read.table-function"><i class="fa fa-check"></i><b>3.4.1</b> The read.table() function</a></li>
<li class="chapter" data-level="3.4.2" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-data"><i class="fa fa-check"></i><b>3.4.2</b> Read data</a></li>
<li class="chapter" data-level="3.4.3" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#about-headertrue-parameter"><i class="fa fa-check"></i><b>3.4.3</b> About header=TRUE parameter</a></li>
<li class="chapter" data-level="3.4.4" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#about-stringsasfactors-false-parameter"><i class="fa fa-check"></i><b>3.4.4</b> About stringsAsFactors = FALSE parameter</a></li>
<li class="chapter" data-level="3.4.5" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#other-useful-parameters"><i class="fa fa-check"></i><b>3.4.5</b> Other useful parameters:</a></li>
<li class="chapter" data-level="3.4.6" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-file-with-unequal-columns-in-first-row-using-read.table."><i class="fa fa-check"></i><b>3.4.6</b> Read file with unequal columns in first row using read.table.</a></li>
<li class="chapter" data-level="3.4.7" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-file-consisting-of-comments-blank-lines-null-values"><i class="fa fa-check"></i><b>3.4.7</b> Read file consisting of comments, blank lines, null values</a></li>
<li class="chapter" data-level="3.4.8" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-csv-file-read.csv"><i class="fa fa-check"></i><b>3.4.8</b> Read csv file read.csv()</a></li>
<li class="chapter" data-level="3.4.9" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#reading-data-from-excel-file"><i class="fa fa-check"></i><b>3.4.9</b> Reading data from excel file</a></li>
<li class="chapter" data-level="3.4.10" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-data-using-readlines"><i class="fa fa-check"></i><b>3.4.10</b> Read data using readLines()</a></li>
<li class="chapter" data-level="3.4.11" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#read-data-using-clipboard-feature"><i class="fa fa-check"></i><b>3.4.11</b> Read data using clipboard feature</a></li>
<li class="chapter" data-level="3.4.12" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#view-data-frame-using-view"><i class="fa fa-check"></i><b>3.4.12</b> View data frame using View()</a></li>
<li class="chapter" data-level="3.4.13" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#edit-data-frame-using-edit"><i class="fa fa-check"></i><b>3.4.13</b> Edit data frame using edit()</a></li>
<li class="chapter" data-level="3.4.14" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#write-r-data-frames-in-a-file-using-write.table"><i class="fa fa-check"></i><b>3.4.14</b> Write R data frames in a file using write.table()</a></li>
<li class="chapter" data-level="3.4.15" data-path="ifforfunctionio.html"><a href="ifforfunctionio.html#write-using-cat"><i class="fa fa-check"></i><b>3.4.15</b> Write using cat()</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-manipulation.html"><a href="data-manipulation.html"><i class="fa fa-check"></i><b>4</b> Data Manipulation</a><ul>
<li class="chapter" data-level="4.1" data-path="data-manipulation.html"><a href="data-manipulation.html#the-apply-function"><i class="fa fa-check"></i><b>4.1</b> The apply() function</a></li>
<li class="chapter" data-level="4.2" data-path="data-manipulation.html"><a href="data-manipulation.html#sapply-function"><i class="fa fa-check"></i><b>4.2</b> sapply() function</a></li>
<li class="chapter" data-level="4.3" data-path="data-manipulation.html"><a href="data-manipulation.html#lapply-function"><i class="fa fa-check"></i><b>4.3</b> lapply() function</a></li>
<li class="chapter" data-level="4.4" data-path="data-manipulation.html"><a href="data-manipulation.html#dplyr-package"><i class="fa fa-check"></i><b>4.4</b> dplyr package</a><ul>
<li class="chapter" data-level="4.4.1" data-path="data-manipulation.html"><a href="data-manipulation.html#load-dplyr-library"><i class="fa fa-check"></i><b>4.4.1</b> Load dplyr library</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-manipulation.html"><a href="data-manipulation.html#load-gene-expression-data"><i class="fa fa-check"></i><b>4.4.2</b> Load Gene Expression Data</a></li>
<li class="chapter" data-level="4.4.3" data-path="data-manipulation.html"><a href="data-manipulation.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>4.4.3</b> Filter rows with filter()</a></li>
<li class="chapter" data-level="4.4.4" data-path="data-manipulation.html"><a href="data-manipulation.html#piping-using"><i class="fa fa-check"></i><b>4.4.4</b> Piping using %&gt;%</a></li>
<li class="chapter" data-level="4.4.5" data-path="data-manipulation.html"><a href="data-manipulation.html#arrange-rows-with-arrange"><i class="fa fa-check"></i><b>4.4.5</b> Arrange rows with arrange()</a></li>
<li class="chapter" data-level="4.4.6" data-path="data-manipulation.html"><a href="data-manipulation.html#select-rows-position-wise-using-slice"><i class="fa fa-check"></i><b>4.4.6</b> Select rows position wise using slice()</a></li>
<li class="chapter" data-level="4.4.7" data-path="data-manipulation.html"><a href="data-manipulation.html#select-column-using-select"><i class="fa fa-check"></i><b>4.4.7</b> Select column using select()</a></li>
<li class="chapter" data-level="4.4.8" data-path="data-manipulation.html"><a href="data-manipulation.html#extract-unique-rows-using-distinct"><i class="fa fa-check"></i><b>4.4.8</b> Extract unique rows using distinct()</a></li>
<li class="chapter" data-level="4.4.9" data-path="data-manipulation.html"><a href="data-manipulation.html#add-new-columns-with-mutate-and-transmute-function"><i class="fa fa-check"></i><b>4.4.9</b> Add new columns with mutate() and transmute() function</a></li>
<li class="chapter" data-level="4.4.10" data-path="data-manipulation.html"><a href="data-manipulation.html#summarise-values-with-summarise"><i class="fa fa-check"></i><b>4.4.10</b> Summarise values with summarise()</a></li>
<li class="chapter" data-level="4.4.11" data-path="data-manipulation.html"><a href="data-manipulation.html#grouped-operations"><i class="fa fa-check"></i><b>4.4.11</b> Grouped operations</a></li>
<li class="chapter" data-level="4.4.12" data-path="data-manipulation.html"><a href="data-manipulation.html#joins-two-table"><i class="fa fa-check"></i><b>4.4.12</b> Joins two table</a></li>
<li class="chapter" data-level="4.4.13" data-path="data-manipulation.html"><a href="data-manipulation.html#references"><i class="fa fa-check"></i><b>4.4.13</b> References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>5</b> Data Visualization</a><ul>
<li class="chapter" data-level="5.1" data-path="data-visualization.html"><a href="data-visualization.html#base-graphics"><i class="fa fa-check"></i><b>5.1</b> Base Graphics</a><ul>
<li class="chapter" data-level="5.1.1" data-path="data-visualization.html"><a href="data-visualization.html#simple-scatter-plot"><i class="fa fa-check"></i><b>5.1.1</b> Simple scatter plot</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-visualization.html"><a href="data-visualization.html#saving-plot"><i class="fa fa-check"></i><b>5.1.2</b> Saving plot</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-visualization.html"><a href="data-visualization.html#add-titlesubtitlex-axis-labely-axis-label-to-plot"><i class="fa fa-check"></i><b>5.1.3</b> Add title/subtitle/x-axis label/y-axis label to plot</a></li>
<li class="chapter" data-level="5.1.4" data-path="data-visualization.html"><a href="data-visualization.html#increase-line-thickness"><i class="fa fa-check"></i><b>5.1.4</b> Increase line thickness</a></li>
<li class="chapter" data-level="5.1.5" data-path="data-visualization.html"><a href="data-visualization.html#assign-color-to-lines-and-points"><i class="fa fa-check"></i><b>5.1.5</b> Assign color to lines and points</a></li>
<li class="chapter" data-level="5.1.6" data-path="data-visualization.html"><a href="data-visualization.html#explore-built-in-colors"><i class="fa fa-check"></i><b>5.1.6</b> Explore built-in colors</a></li>
<li class="chapter" data-level="5.1.7" data-path="data-visualization.html"><a href="data-visualization.html#explore-different-symbols"><i class="fa fa-check"></i><b>5.1.7</b> Explore different symbols</a></li>
<li class="chapter" data-level="5.1.8" data-path="data-visualization.html"><a href="data-visualization.html#explore-different-line-types"><i class="fa fa-check"></i><b>5.1.8</b> Explore different line types</a></li>
<li class="chapter" data-level="5.1.9" data-path="data-visualization.html"><a href="data-visualization.html#rescale-the-x-axis-and-y-axis"><i class="fa fa-check"></i><b>5.1.9</b> Rescale the x-axis and y-axis</a></li>
<li class="chapter" data-level="5.1.10" data-path="data-visualization.html"><a href="data-visualization.html#magnification-of-labels-and-symbols"><i class="fa fa-check"></i><b>5.1.10</b> Magnification of labels and symbols</a></li>
<li class="chapter" data-level="5.1.11" data-path="data-visualization.html"><a href="data-visualization.html#explore-bty-box-type"><i class="fa fa-check"></i><b>5.1.11</b> Explore bty (box type)</a></li>
<li class="chapter" data-level="5.1.12" data-path="data-visualization.html"><a href="data-visualization.html#explore-las-style-of-axis-labels"><i class="fa fa-check"></i><b>5.1.12</b> Explore las (style of axis labels)</a></li>
<li class="chapter" data-level="5.1.13" data-path="data-visualization.html"><a href="data-visualization.html#explore-col.axis-col.lab-col.main-col.sub-parameters"><i class="fa fa-check"></i><b>5.1.13</b> Explore col.axis, col.lab, col.main, col.sub parameters</a></li>
<li class="chapter" data-level="5.1.14" data-path="data-visualization.html"><a href="data-visualization.html#low-level-plotting-functions-lines"><i class="fa fa-check"></i><b>5.1.14</b> Low level plotting functions (lines)</a></li>
<li class="chapter" data-level="5.1.15" data-path="data-visualization.html"><a href="data-visualization.html#low-level-plotting-functions-legend"><i class="fa fa-check"></i><b>5.1.15</b> Low level plotting functions (legend)</a></li>
<li class="chapter" data-level="5.1.16" data-path="data-visualization.html"><a href="data-visualization.html#adding-texts-to-existing-plot-text"><i class="fa fa-check"></i><b>5.1.16</b> Adding texts to existing plot (text)</a></li>
<li class="chapter" data-level="5.1.17" data-path="data-visualization.html"><a href="data-visualization.html#explore-line-plot"><i class="fa fa-check"></i><b>5.1.17</b> Explore Line Plot</a></li>
<li class="chapter" data-level="5.1.18" data-path="data-visualization.html"><a href="data-visualization.html#explore-simple-bar-plot"><i class="fa fa-check"></i><b>5.1.18</b> Explore simple Bar plot</a></li>
<li class="chapter" data-level="5.1.19" data-path="data-visualization.html"><a href="data-visualization.html#explore-stacked-bar-plot"><i class="fa fa-check"></i><b>5.1.19</b> Explore stacked bar plot</a></li>
<li class="chapter" data-level="5.1.20" data-path="data-visualization.html"><a href="data-visualization.html#grouped-bar-plots"><i class="fa fa-check"></i><b>5.1.20</b> Grouped Bar plots</a></li>
<li class="chapter" data-level="5.1.21" data-path="data-visualization.html"><a href="data-visualization.html#histogram"><i class="fa fa-check"></i><b>5.1.21</b> Histogram</a></li>
<li class="chapter" data-level="5.1.22" data-path="data-visualization.html"><a href="data-visualization.html#density-plot"><i class="fa fa-check"></i><b>5.1.22</b> Density plot</a></li>
<li class="chapter" data-level="5.1.23" data-path="data-visualization.html"><a href="data-visualization.html#plot-density-plot-of-two-distributions"><i class="fa fa-check"></i><b>5.1.23</b> Plot density plot of two distributions</a></li>
<li class="chapter" data-level="5.1.24" data-path="data-visualization.html"><a href="data-visualization.html#box-plots"><i class="fa fa-check"></i><b>5.1.24</b> Box plots</a></li>
<li class="chapter" data-level="5.1.25" data-path="data-visualization.html"><a href="data-visualization.html#pie-chart"><i class="fa fa-check"></i><b>5.1.25</b> Pie chart</a></li>
<li class="chapter" data-level="5.1.26" data-path="data-visualization.html"><a href="data-visualization.html#venn-diagram"><i class="fa fa-check"></i><b>5.1.26</b> Venn diagram</a></li>
<li class="chapter" data-level="5.1.27" data-path="data-visualization.html"><a href="data-visualization.html#heatmap"><i class="fa fa-check"></i><b>5.1.27</b> Heatmap</a></li>
<li class="chapter" data-level="5.1.28" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plot-matrices"><i class="fa fa-check"></i><b>5.1.28</b> Scatter plot Matrices</a></li>
<li class="chapter" data-level="5.1.29" data-path="data-visualization.html"><a href="data-visualization.html#ballon-plot"><i class="fa fa-check"></i><b>5.1.29</b> Ballon plot</a></li>
<li class="chapter" data-level="5.1.30" data-path="data-visualization.html"><a href="data-visualization.html#multi-panel-plots"><i class="fa fa-check"></i><b>5.1.30</b> Multi panel plots</a></li>
<li class="chapter" data-level="5.1.31" data-path="data-visualization.html"><a href="data-visualization.html#pca-prinicipal-component-analysis"><i class="fa fa-check"></i><b>5.1.31</b> PCA (Prinicipal Component Analysis)</a></li>
<li class="chapter" data-level="5.1.32" data-path="data-visualization.html"><a href="data-visualization.html#classical-metric-multidimensional-scaling"><i class="fa fa-check"></i><b>5.1.32</b> Classical (Metric) Multidimensional Scaling</a></li>
<li class="chapter" data-level="5.1.33" data-path="data-visualization.html"><a href="data-visualization.html#plotting-k-means"><i class="fa fa-check"></i><b>5.1.33</b> Plotting K-means</a></li>
<li class="chapter" data-level="5.1.34" data-path="data-visualization.html"><a href="data-visualization.html#dendrogram"><i class="fa fa-check"></i><b>5.1.34</b> Dendrogram</a></li>
<li class="chapter" data-level="5.1.35" data-path="data-visualization.html"><a href="data-visualization.html#network-graphs"><i class="fa fa-check"></i><b>5.1.35</b> Network graphs</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-visualization.html"><a href="data-visualization.html#plot-using-ggplot2"><i class="fa fa-check"></i><b>5.2</b> Plot using ggplot2</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>5.2.1</b> Scatter plot</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-visualization.html"><a href="data-visualization.html#add-geom_point-layer"><i class="fa fa-check"></i><b>5.2.2</b> Add geom_point() layer</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-visualization.html"><a href="data-visualization.html#add-geom_smooth-layer-linear-modeling"><i class="fa fa-check"></i><b>5.2.3</b> Add geom_smooth() layer, linear modeling</a></li>
<li class="chapter" data-level="5.2.4" data-path="data-visualization.html"><a href="data-visualization.html#explore-aesthetic-parameter-col"><i class="fa fa-check"></i><b>5.2.4</b> Explore aesthetic parameter “col”</a></li>
<li class="chapter" data-level="5.2.5" data-path="data-visualization.html"><a href="data-visualization.html#assign-aes-to-individual-layer"><i class="fa fa-check"></i><b>5.2.5</b> Assign aes() to individual layer</a></li>
<li class="chapter" data-level="5.2.6" data-path="data-visualization.html"><a href="data-visualization.html#explore-aesthetic-parameter-shape"><i class="fa fa-check"></i><b>5.2.6</b> Explore aesthetic parameter “shape”</a></li>
<li class="chapter" data-level="5.2.7" data-path="data-visualization.html"><a href="data-visualization.html#add-axis-lables-and-plot-title-using-labs"><i class="fa fa-check"></i><b>5.2.7</b> Add axis lables and plot title using labs()</a></li>
<li class="chapter" data-level="5.2.8" data-path="data-visualization.html"><a href="data-visualization.html#change-color-pelette"><i class="fa fa-check"></i><b>5.2.8</b> Change color pelette</a></li>
<li class="chapter" data-level="5.2.9" data-path="data-visualization.html"><a href="data-visualization.html#save-the-ggplot-object-and-then-print."><i class="fa fa-check"></i><b>5.2.9</b> Save the ggplot object and then print.</a></li>
<li class="chapter" data-level="5.2.10" data-path="data-visualization.html"><a href="data-visualization.html#the-theme"><i class="fa fa-check"></i><b>5.2.10</b> The Theme</a></li>
<li class="chapter" data-level="5.2.11" data-path="data-visualization.html"><a href="data-visualization.html#adjusting-the-legend-title"><i class="fa fa-check"></i><b>5.2.11</b> Adjusting the legend title</a></li>
<li class="chapter" data-level="5.2.12" data-path="data-visualization.html"><a href="data-visualization.html#facet_wrap"><i class="fa fa-check"></i><b>5.2.12</b> Facet_wrap</a></li>
<li class="chapter" data-level="5.2.13" data-path="data-visualization.html"><a href="data-visualization.html#bar-charts"><i class="fa fa-check"></i><b>5.2.13</b> Bar charts</a></li>
<li class="chapter" data-level="5.2.14" data-path="data-visualization.html"><a href="data-visualization.html#density-plot-1"><i class="fa fa-check"></i><b>5.2.14</b> Density plot</a></li>
<li class="chapter" data-level="5.2.15" data-path="data-visualization.html"><a href="data-visualization.html#box-plot"><i class="fa fa-check"></i><b>5.2.15</b> Box plot</a></li>
<li class="chapter" data-level="5.2.16" data-path="data-visualization.html"><a href="data-visualization.html#references-1"><i class="fa fa-check"></i><b>5.2.16</b> References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bioconductor.html"><a href="bioconductor.html"><i class="fa fa-check"></i><b>6</b> Bioconductor</a><ul>
<li class="chapter" data-level="6.1" data-path="bioconductor.html"><a href="bioconductor.html#introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="bioconductor.html"><a href="bioconductor.html#install"><i class="fa fa-check"></i><b>6.1.1</b> Install</a></li>
<li class="chapter" data-level="6.1.2" data-path="bioconductor.html"><a href="bioconductor.html#explore-bioconductor-tutorials"><i class="fa fa-check"></i><b>6.1.2</b> Explore Bioconductor Tutorials</a></li>
<li class="chapter" data-level="6.1.3" data-path="bioconductor.html"><a href="bioconductor.html#explore-course-and-conferences-materials"><i class="fa fa-check"></i><b>6.1.3</b> Explore course and conferences materials</a></li>
<li class="chapter" data-level="6.1.4" data-path="bioconductor.html"><a href="bioconductor.html#explore-and-search-for-package-using-biocviews"><i class="fa fa-check"></i><b>6.1.4</b> Explore and Search for package using BiocViews</a></li>
<li class="chapter" data-level="6.1.5" data-path="bioconductor.html"><a href="bioconductor.html#bioconductor-forum"><i class="fa fa-check"></i><b>6.1.5</b> Bioconductor Forum</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bioconductor.html"><a href="bioconductor.html#explore-maftools"><i class="fa fa-check"></i><b>6.2</b> Explore Maftools</a><ul>
<li class="chapter" data-level="6.2.1" data-path="bioconductor.html"><a href="bioconductor.html#about-maftools"><i class="fa fa-check"></i><b>6.2.1</b> About MAFtools</a></li>
<li class="chapter" data-level="6.2.2" data-path="bioconductor.html"><a href="bioconductor.html#about-maf-file"><i class="fa fa-check"></i><b>6.2.2</b> About MAF file</a></li>
<li class="chapter" data-level="6.2.3" data-path="bioconductor.html"><a href="bioconductor.html#install-maftools."><i class="fa fa-check"></i><b>6.2.3</b> Install maftools.</a></li>
<li class="chapter" data-level="6.2.4" data-path="bioconductor.html"><a href="bioconductor.html#load-maftools-library"><i class="fa fa-check"></i><b>6.2.4</b> Load maftools library</a></li>
<li class="chapter" data-level="6.2.5" data-path="bioconductor.html"><a href="bioconductor.html#read-example-maf-file"><i class="fa fa-check"></i><b>6.2.5</b> Read example maf file</a></li>
<li class="chapter" data-level="6.2.6" data-path="bioconductor.html"><a href="bioconductor.html#print-maf-object"><i class="fa fa-check"></i><b>6.2.6</b> Print maf object</a></li>
<li class="chapter" data-level="6.2.7" data-path="bioconductor.html"><a href="bioconductor.html#structure-of-maf-object"><i class="fa fa-check"></i><b>6.2.7</b> Structure of maf object</a></li>
<li class="chapter" data-level="6.2.8" data-path="bioconductor.html"><a href="bioconductor.html#shows-sample-summry."><i class="fa fa-check"></i><b>6.2.8</b> Shows sample summry.</a></li>
<li class="chapter" data-level="6.2.9" data-path="bioconductor.html"><a href="bioconductor.html#show-frequently-mutated-genes."><i class="fa fa-check"></i><b>6.2.9</b> Show frequently mutated genes.</a></li>
<li class="chapter" data-level="6.2.10" data-path="bioconductor.html"><a href="bioconductor.html#shows-all-fields-in-maf"><i class="fa fa-check"></i><b>6.2.10</b> Shows all fields in MAF</a></li>
<li class="chapter" data-level="6.2.11" data-path="bioconductor.html"><a href="bioconductor.html#plotting-maf-summary"><i class="fa fa-check"></i><b>6.2.11</b> Plotting MAF summary</a></li>
<li class="chapter" data-level="6.2.12" data-path="bioconductor.html"><a href="bioconductor.html#oncoplots"><i class="fa fa-check"></i><b>6.2.12</b> Oncoplots</a></li>
<li class="chapter" data-level="6.2.13" data-path="bioconductor.html"><a href="bioconductor.html#transition-and-transversions."><i class="fa fa-check"></i><b>6.2.13</b> Transition and Transversions.</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="bioconductor.html"><a href="bioconductor.html#explore-cummerbund-for-diffrential-gene-expression-analysis"><i class="fa fa-check"></i><b>6.3</b> Explore cummeRbund for Diffrential Gene Expression Analysis</a></li>
<li class="chapter" data-level="6.4" data-path="bioconductor.html"><a href="bioconductor.html#references-2"><i class="fa fa-check"></i><b>6.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html"><i class="fa fa-check"></i><b>7</b> R Case study and Tasks</a><ul>
<li class="chapter" data-level="7.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#case-study1-gene-expression-data-analysis"><i class="fa fa-check"></i><b>7.1</b> Case study1: Gene Expression Data Analysis</a><ul>
<li class="chapter" data-level="7.1.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#experimental-setup"><i class="fa fa-check"></i><b>7.1.1</b> Experimental setup</a></li>
<li class="chapter" data-level="7.1.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#objective"><i class="fa fa-check"></i><b>7.1.2</b> Objective</a></li>
<li class="chapter" data-level="7.1.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#steps"><i class="fa fa-check"></i><b>7.1.3</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#case-study1-solution"><i class="fa fa-check"></i><b>7.2</b> Case study1: Solution</a></li>
<li class="chapter" data-level="7.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#tasks"><i class="fa fa-check"></i><b>7.3</b> Tasks</a><ul>
<li class="chapter" data-level="7.3.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-creation"><i class="fa fa-check"></i><b>7.3.1</b> Vector creation</a></li>
<li class="chapter" data-level="7.3.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#fetching-vector-elements"><i class="fa fa-check"></i><b>7.3.2</b> Fetching vector elements</a></li>
<li class="chapter" data-level="7.3.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-manipulation"><i class="fa fa-check"></i><b>7.3.3</b> Vector manipulation</a></li>
<li class="chapter" data-level="7.3.4" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-arithmetic"><i class="fa fa-check"></i><b>7.3.4</b> Vector arithmetic</a></li>
<li class="chapter" data-level="7.3.5" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#matrix-1"><i class="fa fa-check"></i><b>7.3.5</b> Matrix</a></li>
<li class="chapter" data-level="7.3.6" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#data-frame-1"><i class="fa fa-check"></i><b>7.3.6</b> Data Frame</a></li>
<li class="chapter" data-level="7.3.7" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#tasks-on-iris-data-set"><i class="fa fa-check"></i><b>7.3.7</b> Tasks on Iris data set</a></li>
<li class="chapter" data-level="7.3.8" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#visualization"><i class="fa fa-check"></i><b>7.3.8</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#solutions"><i class="fa fa-check"></i><b>7.4</b> Solutions</a><ul>
<li class="chapter" data-level="7.4.1" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-creation-1"><i class="fa fa-check"></i><b>7.4.1</b> Vector creation</a></li>
<li class="chapter" data-level="7.4.2" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#fetching-vector-elements-1"><i class="fa fa-check"></i><b>7.4.2</b> Fetching vector elements</a></li>
<li class="chapter" data-level="7.4.3" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-manipulation-1"><i class="fa fa-check"></i><b>7.4.3</b> Vector manipulation</a></li>
<li class="chapter" data-level="7.4.4" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#vector-arithmetic-1"><i class="fa fa-check"></i><b>7.4.4</b> Vector arithmetic</a></li>
<li class="chapter" data-level="7.4.5" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#matrix-2"><i class="fa fa-check"></i><b>7.4.5</b> Matrix</a></li>
<li class="chapter" data-level="7.4.6" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#data-frame-2"><i class="fa fa-check"></i><b>7.4.6</b> Data Frame</a></li>
<li class="chapter" data-level="7.4.7" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#tasks-on-iris-data-set-1"><i class="fa fa-check"></i><b>7.4.7</b> Tasks on iris data set</a></li>
<li class="chapter" data-level="7.4.8" data-path="r-case-study-and-tasks.html"><a href="r-case-study-and-tasks.html#visualization-1"><i class="fa fa-check"></i><b>7.4.8</b> Visualization</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>8</b> Descriptive statistics</a><ul>
<li class="chapter" data-level="8.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measure-of-centrality"><i class="fa fa-check"></i><b>8.1</b> Measure of Centrality</a></li>
<li class="chapter" data-level="8.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measure-of-spread"><i class="fa fa-check"></i><b>8.2</b> Measure of Spread</a></li>
<li class="chapter" data-level="8.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#handle-missing-values"><i class="fa fa-check"></i><b>8.3</b> Handle missing values</a><ul>
<li class="chapter" data-level="8.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#shape-data-distribution"><i class="fa fa-check"></i><b>8.3.1</b> Shape / Data Distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#estimate-skewness-and-kurtosis"><i class="fa fa-check"></i><b>8.4</b> Estimate Skewness and Kurtosis</a></li>
<li class="chapter" data-level="8.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#further-with-skewness-and-kurtosis."><i class="fa fa-check"></i><b>8.5</b> Further with Skewness and Kurtosis.</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="data-distributions.html"><a href="data-distributions.html"><i class="fa fa-check"></i><b>9</b> Data Distributions</a><ul>
<li class="chapter" data-level="9.1" data-path="data-distributions.html"><a href="data-distributions.html#normal-distribution"><i class="fa fa-check"></i><b>9.1</b> Normal distribution</a></li>
<li class="chapter" data-level="9.2" data-path="data-distributions.html"><a href="data-distributions.html#effect-of-mean-and-sd-parameter-on-normal-distribution"><i class="fa fa-check"></i><b>9.2</b> Effect of mean and sd parameter on normal distribution</a></li>
<li class="chapter" data-level="9.3" data-path="data-distributions.html"><a href="data-distributions.html#effect-of-n-sample-size-on-normal-distribution"><i class="fa fa-check"></i><b>9.3</b> Effect of n (sample size) on normal distribution</a></li>
<li class="chapter" data-level="9.4" data-path="data-distributions.html"><a href="data-distributions.html#use-z-score-to-calculate-percentile-area-below-or-lower-tail"><i class="fa fa-check"></i><b>9.4</b> Use z score to calculate percentile (area below or lower tail)</a></li>
<li class="chapter" data-level="9.5" data-path="data-distributions.html"><a href="data-distributions.html#use-z-score-to-calculate-upper-tail"><i class="fa fa-check"></i><b>9.5</b> Use z score to calculate Upper tail</a></li>
<li class="chapter" data-level="9.6" data-path="data-distributions.html"><a href="data-distributions.html#given-percentile-area-below-the-curve-or-lower-tail-area-find-the-z-score"><i class="fa fa-check"></i><b>9.6</b> Given percentile (area below the curve or lower tail area), find the z score</a></li>
<li class="chapter" data-level="9.7" data-path="data-distributions.html"><a href="data-distributions.html#explore-the-applet"><i class="fa fa-check"></i><b>9.7</b> Explore the applet</a></li>
<li class="chapter" data-level="9.8" data-path="data-distributions.html"><a href="data-distributions.html#evaluating-the-normal-distribution"><i class="fa fa-check"></i><b>9.8</b> Evaluating the normal distribution</a></li>
<li class="chapter" data-level="9.9" data-path="data-distributions.html"><a href="data-distributions.html#sampling-distribution"><i class="fa fa-check"></i><b>9.9</b> Sampling distribution</a></li>
<li class="chapter" data-level="9.10" data-path="data-distributions.html"><a href="data-distributions.html#standard-error"><i class="fa fa-check"></i><b>9.10</b> Standard Error</a></li>
<li class="chapter" data-level="9.11" data-path="data-distributions.html"><a href="data-distributions.html#confidence-interval"><i class="fa fa-check"></i><b>9.11</b> Confidence interval</a></li>
<li class="chapter" data-level="9.12" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-single-sample-mean"><i class="fa fa-check"></i><b>9.12</b> Hypothesis test for single sample mean</a></li>
<li class="chapter" data-level="9.13" data-path="data-distributions.html"><a href="data-distributions.html#one-tailed-test-greater"><i class="fa fa-check"></i><b>9.13</b> One tailed test (Greater)</a></li>
<li class="chapter" data-level="9.14" data-path="data-distributions.html"><a href="data-distributions.html#one-tailed-test-lesser"><i class="fa fa-check"></i><b>9.14</b> One tailed test (Lesser)</a></li>
<li class="chapter" data-level="9.15" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-two-sample-mean-unpaired"><i class="fa fa-check"></i><b>9.15</b> Hypothesis test for two sample mean, unpaired</a></li>
<li class="chapter" data-level="9.16" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-two-sample-mean-paired"><i class="fa fa-check"></i><b>9.16</b> Hypothesis test for two sample mean, paired</a></li>
<li class="chapter" data-level="9.17" data-path="data-distributions.html"><a href="data-distributions.html#check-for-normality"><i class="fa fa-check"></i><b>9.17</b> Check for normality</a></li>
<li class="chapter" data-level="9.18" data-path="data-distributions.html"><a href="data-distributions.html#check-for-uniform-variance"><i class="fa fa-check"></i><b>9.18</b> Check for uniform variance</a></li>
<li class="chapter" data-level="9.19" data-path="data-distributions.html"><a href="data-distributions.html#hypothesis-test-for-single-sample-proportion"><i class="fa fa-check"></i><b>9.19</b> Hypothesis test for single sample proportion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a><ul>
<li class="chapter" data-level="10.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>10.1</b> Simple linear Regression</a><ul>
<li class="chapter" data-level="10.1.1" data-path="regression.html"><a href="regression.html#build-model"><i class="fa fa-check"></i><b>10.1.1</b> Build model</a></li>
<li class="chapter" data-level="10.1.2" data-path="regression.html"><a href="regression.html#obtain-model-summary-linear-regression-diagnostics"><i class="fa fa-check"></i><b>10.1.2</b> Obtain model summary (Linear Regression Diagnostics)</a></li>
<li class="chapter" data-level="10.1.3" data-path="regression.html"><a href="regression.html#model-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Model coefficients</a></li>
<li class="chapter" data-level="10.1.4" data-path="regression.html"><a href="regression.html#model-significance-and-coefficient-significance"><i class="fa fa-check"></i><b>10.1.4</b> Model significance and Coefficient significance</a></li>
<li class="chapter" data-level="10.1.5" data-path="regression.html"><a href="regression.html#coefficient-of-determination-or-r-squared"><i class="fa fa-check"></i><b>10.1.5</b> Coefficient of Determination or R-squared</a></li>
<li class="chapter" data-level="10.1.6" data-path="regression.html"><a href="regression.html#standard-error-and-f-statistic"><i class="fa fa-check"></i><b>10.1.6</b> Standard Error and F-Statistic</a></li>
<li class="chapter" data-level="10.1.7" data-path="regression.html"><a href="regression.html#aic-and-bic"><i class="fa fa-check"></i><b>10.1.7</b> AIC and BIC</a></li>
<li class="chapter" data-level="10.1.8" data-path="regression.html"><a href="regression.html#residuals-and-residual-plot"><i class="fa fa-check"></i><b>10.1.8</b> Residuals and Residual plot</a></li>
<li class="chapter" data-level="10.1.9" data-path="regression.html"><a href="regression.html#how-to-know-if-the-model-is-best-fit-for-your-data"><i class="fa fa-check"></i><b>10.1.9</b> How to know if the model is best fit for your data?</a></li>
<li class="chapter" data-level="10.1.10" data-path="regression.html"><a href="regression.html#lets-predict-a-new-dataset-using-the-built-model"><i class="fa fa-check"></i><b>10.1.10</b> Lets predict a new dataset using the built model</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>10.2</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="10.2.1" data-path="regression.html"><a href="regression.html#build-multiple-regression-model"><i class="fa fa-check"></i><b>10.2.1</b> Build multiple regression model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>11</b> Clustering</a><ul>
<li class="chapter" data-level="11.1" data-path="clustering.html"><a href="clustering.html#data-preparation"><i class="fa fa-check"></i><b>11.1</b> Data preparation</a><ul>
<li class="chapter" data-level="11.1.1" data-path="clustering.html"><a href="clustering.html#load-library"><i class="fa fa-check"></i><b>11.1.1</b> Load library</a></li>
<li class="chapter" data-level="11.1.2" data-path="clustering.html"><a href="clustering.html#load-tcga-data"><i class="fa fa-check"></i><b>11.1.2</b> Load TCGA data</a></li>
<li class="chapter" data-level="11.1.3" data-path="clustering.html"><a href="clustering.html#vizualize-data"><i class="fa fa-check"></i><b>11.1.3</b> Vizualize data</a></li>
<li class="chapter" data-level="11.1.4" data-path="clustering.html"><a href="clustering.html#data-preparation-1"><i class="fa fa-check"></i><b>11.1.4</b> Data preparation</a></li>
<li class="chapter" data-level="11.1.5" data-path="clustering.html"><a href="clustering.html#check-for-na"><i class="fa fa-check"></i><b>11.1.5</b> Check for NA</a></li>
<li class="chapter" data-level="11.1.6" data-path="clustering.html"><a href="clustering.html#scale-the-data"><i class="fa fa-check"></i><b>11.1.6</b> Scale the data</a></li>
<li class="chapter" data-level="11.1.7" data-path="clustering.html"><a href="clustering.html#vizualize-data-after-scaling"><i class="fa fa-check"></i><b>11.1.7</b> Vizualize data after scaling</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="clustering.html"><a href="clustering.html#clustering-1"><i class="fa fa-check"></i><b>11.2</b> Clustering</a></li>
<li class="chapter" data-level="11.3" data-path="clustering.html"><a href="clustering.html#k-means-clustering"><i class="fa fa-check"></i><b>11.3</b> K-means clustering</a><ul>
<li class="chapter" data-level="11.3.1" data-path="clustering.html"><a href="clustering.html#visualizing-k-means-clusters-in-2d-space"><i class="fa fa-check"></i><b>11.3.1</b> Visualizing k-means clusters in 2D space</a></li>
<li class="chapter" data-level="11.3.2" data-path="clustering.html"><a href="clustering.html#get-details-of-clusters"><i class="fa fa-check"></i><b>11.3.2</b> Get details of clusters</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="clustering.html"><a href="clustering.html#determining-the-optimal-number-of-clusters"><i class="fa fa-check"></i><b>11.4</b> Determining The Optimal Number Of Clusters</a><ul>
<li class="chapter" data-level="11.4.1" data-path="clustering.html"><a href="clustering.html#elbow-method"><i class="fa fa-check"></i><b>11.4.1</b> Elbow method</a></li>
<li class="chapter" data-level="11.4.2" data-path="clustering.html"><a href="clustering.html#average-silhouette-method"><i class="fa fa-check"></i><b>11.4.2</b> Average silhouette method</a></li>
<li class="chapter" data-level="11.4.3" data-path="clustering.html"><a href="clustering.html#gap-statistic-method"><i class="fa fa-check"></i><b>11.4.3</b> Gap statistic method</a></li>
<li class="chapter" data-level="11.4.4" data-path="clustering.html"><a href="clustering.html#nbclust-function-30-indices-for-choosing-the-best-number-of-clusters"><i class="fa fa-check"></i><b>11.4.4</b> NbClust() function: 30 indices for choosing the best number of clusters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>12</b> PCA</a><ul>
<li class="chapter" data-level="12.1" data-path="pca.html"><a href="pca.html#about-principal-component-analysis-pca"><i class="fa fa-check"></i><b>12.1</b> About Principal Component Analysis (PCA</a></li>
<li class="chapter" data-level="12.2" data-path="pca.html"><a href="pca.html#data-preparation-2"><i class="fa fa-check"></i><b>12.2</b> Data preparation</a><ul>
<li class="chapter" data-level="12.2.1" data-path="pca.html"><a href="pca.html#load-gene-expression-data-from-tcga-breast-cancer"><i class="fa fa-check"></i><b>12.2.1</b> Load Gene expression data from TCGA Breast cancer</a></li>
<li class="chapter" data-level="12.2.2" data-path="pca.html"><a href="pca.html#data-standardization"><i class="fa fa-check"></i><b>12.2.2</b> Data standardization</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="pca.html"><a href="pca.html#perform-pca"><i class="fa fa-check"></i><b>12.3</b> Perform PCA</a></li>
<li class="chapter" data-level="12.4" data-path="pca.html"><a href="pca.html#visualization-and-interpretation"><i class="fa fa-check"></i><b>12.4</b> Visualization and Interpretation</a></li>
<li class="chapter" data-level="12.5" data-path="pca.html"><a href="pca.html#eigenvalues-variances-number-of-pcs-to-consider"><i class="fa fa-check"></i><b>12.5</b> Eigenvalues / Variances / Number of PCs to consider</a></li>
<li class="chapter" data-level="12.6" data-path="pca.html"><a href="pca.html#graph-of-variables"><i class="fa fa-check"></i><b>12.6</b> Graph of variables</a></li>
<li class="chapter" data-level="12.7" data-path="pca.html"><a href="pca.html#correlation-circle"><i class="fa fa-check"></i><b>12.7</b> Correlation circle</a></li>
<li class="chapter" data-level="12.8" data-path="pca.html"><a href="pca.html#quality-of-representation"><i class="fa fa-check"></i><b>12.8</b> Quality of representation</a></li>
<li class="chapter" data-level="12.9" data-path="pca.html"><a href="pca.html#referece"><i class="fa fa-check"></i><b>12.9</b> Referece</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="network-analysis.html"><a href="network-analysis.html"><i class="fa fa-check"></i><b>13</b> Network analysis</a><ul>
<li class="chapter" data-level="13.1" data-path="network-analysis.html"><a href="network-analysis.html#data-processing"><i class="fa fa-check"></i><b>13.1</b> Data processing</a><ul>
<li class="chapter" data-level="13.1.1" data-path="network-analysis.html"><a href="network-analysis.html#load-igraph-library"><i class="fa fa-check"></i><b>13.1.1</b> Load iGraph Library</a></li>
<li class="chapter" data-level="13.1.2" data-path="network-analysis.html"><a href="network-analysis.html#load-data"><i class="fa fa-check"></i><b>13.1.2</b> Load data</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="network-analysis.html"><a href="network-analysis.html#convert-data-frame-to-graph"><i class="fa fa-check"></i><b>13.2</b> Convert data frame to graph</a></li>
<li class="chapter" data-level="13.3" data-path="network-analysis.html"><a href="network-analysis.html#node-and-edge-details"><i class="fa fa-check"></i><b>13.3</b> Node and Edge details</a></li>
<li class="chapter" data-level="13.4" data-path="network-analysis.html"><a href="network-analysis.html#plot-parameters"><i class="fa fa-check"></i><b>13.4</b> Plot Parameters</a></li>
<li class="chapter" data-level="13.5" data-path="network-analysis.html"><a href="network-analysis.html#network-layouts"><i class="fa fa-check"></i><b>13.5</b> Network layouts</a></li>
<li class="chapter" data-level="13.6" data-path="network-analysis.html"><a href="network-analysis.html#network-and-node-descriptives"><i class="fa fa-check"></i><b>13.6</b> Network and node descriptives</a><ul>
<li class="chapter" data-level="13.6.1" data-path="network-analysis.html"><a href="network-analysis.html#edge-density"><i class="fa fa-check"></i><b>13.6.1</b> Edge density</a></li>
<li class="chapter" data-level="13.6.2" data-path="network-analysis.html"><a href="network-analysis.html#diameter"><i class="fa fa-check"></i><b>13.6.2</b> Diameter</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="network-analysis.html"><a href="network-analysis.html#centrality-centralization"><i class="fa fa-check"></i><b>13.7</b> Centrality &amp; centralization</a><ul>
<li class="chapter" data-level="13.7.1" data-path="network-analysis.html"><a href="network-analysis.html#degree-centrality"><i class="fa fa-check"></i><b>13.7.1</b> Degree centrality</a></li>
<li class="chapter" data-level="13.7.2" data-path="network-analysis.html"><a href="network-analysis.html#closeness"><i class="fa fa-check"></i><b>13.7.2</b> Closeness</a></li>
<li class="chapter" data-level="13.7.3" data-path="network-analysis.html"><a href="network-analysis.html#betweenness"><i class="fa fa-check"></i><b>13.7.3</b> Betweenness</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="network-analysis.html"><a href="network-analysis.html#hubs-and-authorities"><i class="fa fa-check"></i><b>13.8</b> Hubs and authorities</a></li>
<li class="chapter" data-level="13.9" data-path="network-analysis.html"><a href="network-analysis.html#distances-and-paths"><i class="fa fa-check"></i><b>13.9</b> Distances and paths</a></li>
<li class="chapter" data-level="13.10" data-path="network-analysis.html"><a href="network-analysis.html#cliques"><i class="fa fa-check"></i><b>13.10</b> Cliques</a></li>
<li class="chapter" data-level="13.11" data-path="network-analysis.html"><a href="network-analysis.html#community-detection"><i class="fa fa-check"></i><b>13.11</b> Community detection</a></li>
<li class="chapter" data-level="13.12" data-path="network-analysis.html"><a href="network-analysis.html#interative-network"><i class="fa fa-check"></i><b>13.12</b> Interative network</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://biosakshat.weebly.com" target="blank">Visit site</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BioSakshat - Free Study Materials</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1">
<h1><span class="header-section-number">Chapter 10</span> Regression</h1>
<div id="simple-linear-regression" class="section level2">
<h2><span class="header-section-number">10.1</span> Simple linear Regression</h2>
<div id="build-model" class="section level3">
<h3><span class="header-section-number">10.1.1</span> Build model</h3>
<div class="sourceCode" id="cb947"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb947-1" data-line-number="1"><span class="kw">head</span>(faithful);</a></code></pre></div>
<pre><code>##   eruptions waiting
## 1     3.600      79
## 2     1.800      54
## 3     3.333      74
## 4     2.283      62
## 5     4.533      85
## 6     2.883      55</code></pre>
<div class="sourceCode" id="cb949"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb949-1" data-line-number="1">eruption.lm =<span class="st"> </span><span class="kw">lm</span>(eruptions<span class="op">~</span>waiting, <span class="dt">data =</span> faithful);</a>
<a class="sourceLine" id="cb949-2" data-line-number="2"><span class="kw">print</span>(eruption.lm);</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eruptions ~ waiting, data = faithful)
## 
## Coefficients:
## (Intercept)      waiting  
##    -1.87402      0.07563</code></pre>
<p>Now that we have built the linear model, we also have established the relationship between the predictor and response in the form of a mathematical formula for eruptions as a function for waiting time.</p>
<p>For the above output, you can notice the <strong>‘Coefficients’</strong> part having two components: <strong><em>Intercept</em></strong>: -1.87402, <strong><em>waiting</em></strong>: 0.07563. These are also called the beta coefficients. In other words,</p>
<p>eruptions = Intercept + (β ∗ waiting)</p>
<p>eruptions = −1.87402 + 0.07563∗ waiting</p>
</div>
<div id="obtain-model-summary-linear-regression-diagnostics" class="section level3">
<h3><span class="header-section-number">10.1.2</span> Obtain model summary (Linear Regression Diagnostics)</h3>
<div class="sourceCode" id="cb951"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb951-1" data-line-number="1"><span class="co"># Obtain model summary</span></a>
<a class="sourceLine" id="cb951-2" data-line-number="2">eruption.lm.summary =<span class="st"> </span><span class="kw">summary</span>(eruption.lm)</a>
<a class="sourceLine" id="cb951-3" data-line-number="3">eruption.lm.summary;</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eruptions ~ waiting, data = faithful)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.29917 -0.37689  0.03508  0.34909  1.19329 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.874016   0.160143  -11.70   &lt;2e-16 ***
## waiting      0.075628   0.002219   34.09   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4965 on 270 degrees of freedom
## Multiple R-squared:  0.8115, Adjusted R-squared:  0.8108 
## F-statistic:  1162 on 1 and 270 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now the linear model is built and we have a formula that we can use to predict the dist value if a corresponding speed is known. Is this enough to actually use this model? NO! Before using a regression model, you have to ensure that it is statistically significant. How do you ensure this?</p>
<p>We need to understand the following parameters</p>
<ol style="list-style-type: decimal">
<li>model coefficients</li>
<li>Statistical significance of overrall model (model p value)</li>
<li>Statistical significance of individual coefficients (p value of coefficients)</li>
<li>t statistics or test statistics</li>
<li>Residuals and Standard residuals</li>
<li>R-squared and Adjusted R-squared</li>
<li>Residual standard error</li>
<li>AIC and BIC</li>
<li>Use the model to predict new dataset</li>
</ol>
<p>We will explore these one by one</p>
<p><br></p>
</div>
<div id="model-coefficients" class="section level3">

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- horizontal -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3848514720264642"
     data-ad-slot="8864343484"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


<h3><span class="header-section-number">10.1.3</span> Model coefficients</h3>
<div class="sourceCode" id="cb953"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb953-1" data-line-number="1"><span class="co"># From the result fetch coefficients</span></a>
<a class="sourceLine" id="cb953-2" data-line-number="2">coeffs =<span class="st"> </span>eruption.lm<span class="op">$</span>coefficients;</a>
<a class="sourceLine" id="cb953-3" data-line-number="3">coeffs</a></code></pre></div>
<pre><code>## (Intercept)     waiting 
## -1.87401599  0.07562795</code></pre>
<div class="sourceCode" id="cb955"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb955-1" data-line-number="1"><span class="co"># Use coefficients function</span></a>
<a class="sourceLine" id="cb955-2" data-line-number="2">coeffs =<span class="st"> </span><span class="kw">coefficients</span>(eruption.lm); </a>
<a class="sourceLine" id="cb955-3" data-line-number="3">coeffs </a></code></pre></div>
<pre><code>## (Intercept)     waiting 
## -1.87401599  0.07562795</code></pre>
<p><br></p>
</div>
<div id="model-significance-and-coefficient-significance" class="section level3">
<h3><span class="header-section-number">10.1.4</span> Model significance and Coefficient significance</h3>
<p><br>
The summary statistics above tells us a number of things. One of them is the <strong>model p-Value (bottom last line)</strong> and the <strong>p-Value of individual predictor variables</strong> (extreme right column under ‘Coefficients’).</p>
<p><strong>p-Values</strong> are very important because, We can consider a linear model to be statistically significant only when both these p-Values are less that the pre-determined statistical significance level, which is ideally 0.05. This is visually interpreted by the significance stars at the end of the row. The more the stars beside the variable’s p-Value, the more significant the variable.</p>
<p><strong>Null and alternate hypothesis :</strong> In Linear Regression, the Null Hypothesis is that the coefficients associated with the variables is equal to zero. The alternate hypothesis is that the coefficients are not equal to zero (i.e. there exists a relationship between the independent variable in question and the dependent variable).</p>
<p>Check pvalue and based on significance level (e.g. 0.05) decide whether to reject null hypothesis or not. If p value is &lt; significance level (e.g. 0.05), we can say that there is a strong evidence exist to reject the null hypothesis and we are 95% confident about this.</p>
<p>You can see that p value of model is 2.2e-16 which is &lt; 0.05 so we can reject null hypothesis (beta coefficients are zero i.e. slope is 0 i.e. no relation between X and Y i.e. no relation between explanatory and dependent variable). Hence there is a significant relationship between the variables in the linear regression model of the data set faithful.</p>
<p>t-value</p>
<p>We can interpret the t-value something like this. A larger t-value indicates that it is less likely that the coefficient is not equal to zero purely by chance. So, higher the t-value, the better.</p>
<p>Pr(&gt;|t|) or p-value is the probability that you get a t-value as high or higher than the observed value when the Null Hypothesis (the β coefficient is equal to zero or that there is no relationship) is true. So if the Pr(&gt;|t|) is low, the coefficients are significant (significantly different from zero). If the Pr(&gt;|t|) is high, the coefficients are not significant.</p>
<p>It is absolutely important for the model to be statistically significant before we can go ahead and use it to predict (or estimate) the dependent variable, otherwise, the confidence in predicted values from that model reduces and may be construed as an event of chance.</p>
<p><br></p>
</div>
<div id="coefficient-of-determination-or-r-squared" class="section level3">
<h3><span class="header-section-number">10.1.5</span> Coefficient of Determination or R-squared</h3>
<p>The actual information in a data is the total variation it contains. What R-Squared/coefficient of determination tells us is the proportion of variation in the dependent (response) variable that has been explained by this model. Higher the value, better is the model fit to data. We don’t necessarily discard a model based on a low R-Squared value. Its a better practice to look at the AIC and prediction accuracy on validation sample when deciding on the efficacy of a model.</p>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb957-1" data-line-number="1">eruption.lm.summary =<span class="st"> </span><span class="kw">summary</span>(eruption.lm);</a>
<a class="sourceLine" id="cb957-2" data-line-number="2"><span class="kw">str</span>(eruption.lm.summary);</a></code></pre></div>
<pre><code>## List of 11
##  $ call         : language lm(formula = eruptions ~ waiting, data = faithful)
##  $ terms        :Classes &#39;terms&#39;, &#39;formula&#39;  language eruptions ~ waiting
##   .. ..- attr(*, &quot;variables&quot;)= language list(eruptions, waiting)
##   .. ..- attr(*, &quot;factors&quot;)= int [1:2, 1] 0 1
##   .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. .. ..$ : chr [1:2] &quot;eruptions&quot; &quot;waiting&quot;
##   .. .. .. ..$ : chr &quot;waiting&quot;
##   .. ..- attr(*, &quot;term.labels&quot;)= chr &quot;waiting&quot;
##   .. ..- attr(*, &quot;order&quot;)= int 1
##   .. ..- attr(*, &quot;intercept&quot;)= int 1
##   .. ..- attr(*, &quot;response&quot;)= int 1
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##   .. ..- attr(*, &quot;predvars&quot;)= language list(eruptions, waiting)
##   .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:2] &quot;numeric&quot; &quot;numeric&quot;
##   .. .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;eruptions&quot; &quot;waiting&quot;
##  $ residuals    : Named num [1:272] -0.5006 -0.4099 -0.3895 -0.5319 -0.0214 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:272] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##  $ coefficients : num [1:2, 1:4] -1.87402 0.07563 0.16014 0.00222 -11.70212 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;waiting&quot;
##   .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot; &quot;Pr(&gt;|t|)&quot;
##  $ aliased      : Named logi [1:2] FALSE FALSE
##   ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;(Intercept)&quot; &quot;waiting&quot;
##  $ sigma        : num 0.497
##  $ df           : int [1:3] 2 270 2
##  $ r.squared    : num 0.811
##  $ adj.r.squared: num 0.811
##  $ fstatistic   : Named num [1:3] 1162 1 270
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;
##  $ cov.unscaled : num [1:2, 1:2] 0.10403 -0.00142 -0.00142 0.00002
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;waiting&quot;
##   .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;waiting&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</code></pre>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb959-1" data-line-number="1"><span class="kw">print</span>(eruption.lm.summary<span class="op">$</span>r.squared);</a></code></pre></div>
<pre><code>## [1] 0.8114608</code></pre>
<p><strong>Now thats about R-Squared. What about adjusted R-Squared?</strong> As you add more X variables to your model, the R-Squared value of the new bigger model will always be greater than that of the smaller subset. This is because, since all the variables in the original model is also present, their contribution to explain the dependent variable will be present in the super-set as well, therefore, whatever new variable we add can only add (if not significantly) to the variation that was already explained. It is here, the adjusted R-Squared value comes to help. Adj R-Squared penalizes total value for the number of terms (read predictors) in your model. Therefore when comparing nested models, it is a good practice to look at adj-R-squared value over R-squared.</p>
<p>In this example since we had only one explanatory variable i.e. waiting, both R-squared and adjusted R-squared value remains same.</p>
<p><br></p>
</div>
<div id="standard-error-and-f-statistic" class="section level3">
<h3><span class="header-section-number">10.1.6</span> Standard Error and F-Statistic</h3>
<p>Both standard errors and F-statistic are measures of goodness of fit.
Standard error should be low (Closer to 0 is better) and higher F-statistics is better.</p>
<div class="sourceCode" id="cb961"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb961-1" data-line-number="1">eruption.lm.summary;</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eruptions ~ waiting, data = faithful)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.29917 -0.37689  0.03508  0.34909  1.19329 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.874016   0.160143  -11.70   &lt;2e-16 ***
## waiting      0.075628   0.002219   34.09   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4965 on 270 degrees of freedom
## Multiple R-squared:  0.8115, Adjusted R-squared:  0.8108 
## F-statistic:  1162 on 1 and 270 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb963-1" data-line-number="1">eruption.lm.summary<span class="op">$</span>fstatistic;</a></code></pre></div>
<pre><code>##    value    numdf    dendf 
## 1162.063    1.000  270.000</code></pre>
<p>Here numdf is numerator degree of freedom [number of variables - 1]. We have two variables, eruptions and waiting. So numdf = 2-1 i.e. 1</p>
<p>dendf is denominator degree of freedom which is number of observations - number of variables. dim(faithful) says 272 observations. So 272-number of variables i.e. 272-2 = 270.</p>
<p><br></p>
</div>
<div id="aic-and-bic" class="section level3">
<h3><span class="header-section-number">10.1.7</span> AIC and BIC</h3>
<p>The Akaike’s information criterion - AIC (Akaike, 1974) and the Bayesian information criterion - BIC (Schwarz, 1978) are measures of the goodness of fit of an estimated statistical model and can also be used for model selection.</p>
<p>For model comparison, the model with the lowest AIC and BIC score is preferred.</p>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb965-1" data-line-number="1"><span class="kw">AIC</span>(<span class="dt">object =</span> eruption.lm);</a></code></pre></div>
<pre><code>## [1] 395.0159</code></pre>
<div class="sourceCode" id="cb967"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb967-1" data-line-number="1"><span class="kw">BIC</span>(<span class="dt">object =</span> eruption.lm);</a></code></pre></div>
<pre><code>## [1] 405.8333</code></pre>
<p><br></p>
</div>
<div id="residuals-and-residual-plot" class="section level3">
<h3><span class="header-section-number">10.1.8</span> Residuals and Residual plot</h3>
<p><br></p>
<p>Residual is the difference between observed and predicted value of y.</p>
<div class="sourceCode" id="cb969"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb969-1" data-line-number="1"><span class="co"># Obtain residual using model object</span></a>
<a class="sourceLine" id="cb969-2" data-line-number="2"><span class="kw">head</span>(eruption.lm<span class="op">$</span>residuals);</a></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
## -0.50059190 -0.40989320 -0.38945216 -0.53191679 -0.02135959  0.59747885</code></pre>
<div class="sourceCode" id="cb971"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb971-1" data-line-number="1"><span class="co"># Obtain residual using function</span></a>
<a class="sourceLine" id="cb971-2" data-line-number="2"><span class="kw">head</span>(<span class="kw">resid</span>(eruption.lm))</a></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
## -0.50059190 -0.40989320 -0.38945216 -0.53191679 -0.02135959  0.59747885</code></pre>
<p><br></p>
<p><strong>Residual plot</strong></p>
<div class="sourceCode" id="cb973"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb973-1" data-line-number="1">X =<span class="st"> </span>faithful<span class="op">$</span>waiting;</a>
<a class="sourceLine" id="cb973-2" data-line-number="2">Y =<span class="st"> </span><span class="kw">resid</span>(eruption.lm);</a>
<a class="sourceLine" id="cb973-3" data-line-number="3"><span class="kw">plot</span>(X,Y, <span class="dt">xlab=</span><span class="st">&quot;Waiting Time&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Residuals&quot;</span>);</a>
<a class="sourceLine" id="cb973-4" data-line-number="4"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>);</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-244-1.png" width="672" />
It can be seen that there are much difference between observed and predicted value.</p>
<p><strong>Standardized Residual</strong></p>
<p>The standardized residual is the residual divided by its standard deviation.</p>
<div class="sourceCode" id="cb974"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb974-1" data-line-number="1">rstd =<span class="st"> </span><span class="kw">rstandard</span>(eruption.lm)</a>
<a class="sourceLine" id="cb974-2" data-line-number="2"><span class="kw">head</span>(rstd);</a></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
## -1.01073883 -0.82944175 -0.78589633 -1.07413200 -0.04318464  1.20863241</code></pre>
<div class="sourceCode" id="cb976"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb976-1" data-line-number="1">X =<span class="st"> </span>faithful<span class="op">$</span>waiting;</a>
<a class="sourceLine" id="cb976-2" data-line-number="2">Y =<span class="st"> </span>rstd;</a>
<a class="sourceLine" id="cb976-3" data-line-number="3"><span class="kw">plot</span>(X,Y, <span class="dt">xlab=</span><span class="st">&quot;Waiting Time&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Standardized Residual&quot;</span>);</a>
<a class="sourceLine" id="cb976-4" data-line-number="4"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>);</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-245-1.png" width="672" /></p>
<p><strong>Normal Probability Plot of Residuals</strong></p>
<p>Check whether the residuals show normal distribution or not?</p>
<div class="sourceCode" id="cb977"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb977-1" data-line-number="1"><span class="kw">qqnorm</span>(rstd, <span class="dt">ylab=</span><span class="st">&quot;Standardized Residuals&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Normal Scores&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Old Faithful Eruptions (QQ plot)&quot;</span>) </a>
<a class="sourceLine" id="cb977-2" data-line-number="2"><span class="kw">qqline</span>(rstd) </a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-246-1.png" width="672" /></p>
<p><br></p>
<p><strong>Correlation between observed and predicted Y (Model fitness)</strong></p>
<div class="sourceCode" id="cb978"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb978-1" data-line-number="1">Ypred =<span class="st"> </span><span class="kw">resid</span>(eruption.lm);</a>
<a class="sourceLine" id="cb978-2" data-line-number="2">Ytrue =<span class="st"> </span>faithful<span class="op">$</span>eruptions;</a>
<a class="sourceLine" id="cb978-3" data-line-number="3"><span class="co"># Correlation testing</span></a>
<a class="sourceLine" id="cb978-4" data-line-number="4"><span class="kw">cor.test</span>(Ytrue, Ypred);</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Ytrue and Ypred
## t = 7.9204, df = 270, p-value = 6.204e-14
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3324440 0.5259831
## sample estimates:
##       cor 
## 0.4342111</code></pre>
<p>Correlation: 0.43 suggesting positive correlation</p>
<p>Pvalue &lt; 0.05 suggesting significant association</p>
<p><br></p>
<p><strong>Correlation plot</strong></p>
<div class="sourceCode" id="cb980"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb980-1" data-line-number="1"><span class="kw">plot</span>(Ytrue, Ypred, <span class="dt">xlab=</span><span class="st">&quot;True Eruption&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Predicted Eruption&quot;</span>);</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-248-1.png" width="672" /></p>
</div>
<div id="how-to-know-if-the-model-is-best-fit-for-your-data" class="section level3">

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- horizontal -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3848514720264642"
     data-ad-slot="8864343484"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


<h3><span class="header-section-number">10.1.9</span> How to know if the model is best fit for your data?</h3>
<p><img src="image/model_evaluation.png" /></p>
<p>source: <a href="http://r-statistics.co/Linear-Regression.html" class="uri">http://r-statistics.co/Linear-Regression.html</a></p>
<p><br></p>
</div>
<div id="lets-predict-a-new-dataset-using-the-built-model" class="section level3">
<h3><span class="header-section-number">10.1.10</span> Lets predict a new dataset using the built model</h3>
<div class="sourceCode" id="cb981"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb981-1" data-line-number="1">testdata =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">waiting=</span><span class="dv">80</span>);</a>
<a class="sourceLine" id="cb981-2" data-line-number="2">testdata;</a></code></pre></div>
<pre><code>##   waiting
## 1      80</code></pre>
<div class="sourceCode" id="cb983"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb983-1" data-line-number="1"><span class="kw">predict</span>(<span class="dt">object =</span> eruption.lm, <span class="dt">newdata =</span> testdata)</a></code></pre></div>
<pre><code>##       1 
## 4.17622</code></pre>
<div class="sourceCode" id="cb985"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb985-1" data-line-number="1"><span class="co"># Lets manually predict based on coefficients</span></a>
<a class="sourceLine" id="cb985-2" data-line-number="2"><span class="kw">print</span>(coeffs)</a></code></pre></div>
<pre><code>## (Intercept)     waiting 
## -1.87401599  0.07562795</code></pre>
<div class="sourceCode" id="cb987"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb987-1" data-line-number="1">coeffs[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>coeffs[<span class="dv">2</span>]<span class="op">*</span>testdata[<span class="dv">1</span>,<span class="dv">1</span>];  <span class="co"># intercept + slope * x</span></a></code></pre></div>
<pre><code>## (Intercept) 
##     4.17622</code></pre>
<p><strong>Confidence Interval and Prediction interval for Linear Regression</strong></p>
<p>Assume that the error term ϵ in the simple linear regression model is independent of x, and is normally distributed, with zero mean and constant variance.</p>
<p>For a given value of x, the <strong>interval estimate</strong> of the <strong>dependent variable y</strong> is called the <strong><em>prediction interval</em></strong>.</p>
<p>For a given value of x, the <strong>interval estimate</strong> for the <strong>mean of the dependent variable</strong>, ¯y , is called the <strong><em>confidence interval</em></strong>.</p>
<p>Using the testdataset, predict the 95% prediction interval of the <strong>eruption</strong> and 95% confidence interval for <strong>mean eruption</strong>, for the waiting time 80.</p>
<div class="sourceCode" id="cb989"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb989-1" data-line-number="1">testdata;</a></code></pre></div>
<pre><code>##   waiting
## 1      80</code></pre>
<div class="sourceCode" id="cb991"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb991-1" data-line-number="1"><span class="co"># The 95% confidence interval of the mean eruption duration for the waiting time of 80 minutes is between 4.1048 and 4.2476 minutes. </span></a>
<a class="sourceLine" id="cb991-2" data-line-number="2"><span class="kw">predict</span>(<span class="dt">object =</span> eruption.lm, <span class="dt">newdata =</span> testdata, <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>);</a></code></pre></div>
<pre><code>##       fit      lwr      upr
## 1 4.17622 4.104848 4.247592</code></pre>
<div class="sourceCode" id="cb993"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb993-1" data-line-number="1"><span class="co">#The 95% prediction interval of the eruption duration for the waiting time of 80 minutes is between 3.1961 and 5.1564 minutes. </span></a>
<a class="sourceLine" id="cb993-2" data-line-number="2"><span class="kw">predict</span>(<span class="dt">object =</span> eruption.lm, <span class="dt">newdata =</span> testdata, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>);</a></code></pre></div>
<pre><code>##       fit      lwr      upr
## 1 4.17622 3.196089 5.156351</code></pre>
</div>
</div>
<div id="multiple-linear-regression" class="section level2">

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- horizontal -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3848514720264642"
     data-ad-slot="8864343484"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


<h2><span class="header-section-number">10.2</span> Multiple Linear Regression</h2>
<p>A multiple linear regression (MLR) model describes a dependent variable y by independent variables x1, x2, …, xp (p &gt; 1).</p>
<p>Lets consider stackloss dataset desribing observations from a chemical plant operation.</p>
<p>stackloss is a data frame with 21 observations on 4 variables.</p>
<ol style="list-style-type: decimal">
<li>Air Flow Flow of cooling air</li>
<li>Water Temp Cooling Water Inlet Temperature</li>
<li>Acid Conc. Concentration of acid [per 1000, minus 500]</li>
<li>stack.loss Stack loss</li>
</ol>
<p>“Obtained from 21 days of operation of a plant for the oxidation of ammonia (NH3) to nitric acid (HNO3). The nitric oxides produced are absorbed in a countercurrent absorption tower”. For details type ?stackloss</p>
<div class="sourceCode" id="cb995"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb995-1" data-line-number="1"><span class="kw">head</span>(stackloss);</a></code></pre></div>
<pre><code>##   Air.Flow Water.Temp Acid.Conc. stack.loss
## 1       80         27         89         42
## 2       80         27         88         37
## 3       75         25         90         37
## 4       62         24         87         28
## 5       62         22         87         18
## 6       62         23         87         18</code></pre>
<div id="build-multiple-regression-model" class="section level3">
<h3><span class="header-section-number">10.2.1</span> Build multiple regression model</h3>
<p>In this model we try to predict stack loss (y) using x (air flow, water temp and acid conc). Lets change the column labels.</p>
<div class="sourceCode" id="cb997"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb997-1" data-line-number="1"><span class="kw">colnames</span>(stackloss) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Airflow&quot;</span>,<span class="st">&quot;Watertemp&quot;</span>,<span class="st">&quot;Acidconc&quot;</span>,<span class="st">&quot;Stackloss&quot;</span>)</a>
<a class="sourceLine" id="cb997-2" data-line-number="2"><span class="kw">head</span>(stackloss);</a></code></pre></div>
<pre><code>##   Airflow Watertemp Acidconc Stackloss
## 1      80        27       89        42
## 2      80        27       88        37
## 3      75        25       90        37
## 4      62        24       87        28
## 5      62        22       87        18
## 6      62        23       87        18</code></pre>
<div class="sourceCode" id="cb999"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb999-1" data-line-number="1">stackloss.lm =<span class="st"> </span><span class="kw">lm</span>(Stackloss <span class="op">~</span><span class="st"> </span>Airflow <span class="op">+</span><span class="st"> </span>Watertemp <span class="op">+</span><span class="st"> </span>Acidconc, <span class="dt">data=</span>stackloss);</a>
<a class="sourceLine" id="cb999-2" data-line-number="2">stackloss.lm;</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Stackloss ~ Airflow + Watertemp + Acidconc, data = stackloss)
## 
## Coefficients:
## (Intercept)      Airflow    Watertemp     Acidconc  
##    -39.9197       0.7156       1.2953      -0.1521</code></pre>
<p>We have now 4 coefficients.</p>
<ol style="list-style-type: decimal">
<li>Intercept</li>
<li>Airflow</li>
<li>Watertemp</li>
<li>Acidconc</li>
</ol>
<p>Lets summarise the model</p>
<div class="sourceCode" id="cb1001"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1001-1" data-line-number="1"><span class="kw">summary</span>(stackloss.lm);</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Stackloss ~ Airflow + Watertemp + Acidconc, data = stackloss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.2377 -1.7117 -0.4551  2.3614  5.6978 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -39.9197    11.8960  -3.356  0.00375 ** 
## Airflow       0.7156     0.1349   5.307  5.8e-05 ***
## Watertemp     1.2953     0.3680   3.520  0.00263 ** 
## Acidconc     -0.1521     0.1563  -0.973  0.34405    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.243 on 17 degrees of freedom
## Multiple R-squared:  0.9136, Adjusted R-squared:  0.8983 
## F-statistic:  59.9 on 3 and 17 DF,  p-value: 3.016e-09</code></pre>
<p><br></p>
<p><strong>Model significance</strong></p>
<p>Model pvalue observed is 3.016e-09. So model is significant at 0.05 significance level. so we are 95% confident that prediction of Y from X is significant i.e. there is definitely some degree of association exists between Y and X.</p>
<p><strong>Coefficients significance</strong></p>
<ol style="list-style-type: decimal">
<li>Intercept pvalue is 0.00375 (&lt; 0.05) so significant **</li>
<li>Airflow pvalue 5.8e-05 (&lt; 0.001) so highly significant ***</li>
<li>Watertemp pvalue 0.00263 (, 0.05) so significant **</li>
<li>Acidconc pvalue 0.34405 (&gt; 0.05) so not significant</li>
</ol>
<p>So except Acidconc, we can say with 95% confidence that for other variables like Airflow and Watertemp, some degree of association with Stackloss exists.</p>
<p><strong>R-squared</strong></p>
<p>Multiple R-squared: 0.9136 means the regression model explains 91% of data variation. However since multiple X variables are involved, we should look at adjusted R-squared values (0.8983)</p>
<p><strong>Residual standard error</strong></p>
<p>3.243 on 17 degree of freedom. This may not be useful for a single model, however we can use this to compare the model with other alternative models.</p>
<p><strong>Use model to predict test dataset</strong></p>
<div class="sourceCode" id="cb1003"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1003-1" data-line-number="1">testdata =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Airflow=</span><span class="dv">72</span>, <span class="dt">Watertemp=</span><span class="dv">20</span>, <span class="dt">Acidconc=</span><span class="dv">85</span>) </a>
<a class="sourceLine" id="cb1003-2" data-line-number="2">testdata_result =<span class="st"> </span><span class="kw">predict</span>(<span class="dt">object =</span> stackloss.lm, testdata);</a>
<a class="sourceLine" id="cb1003-3" data-line-number="3">testdata_result;</a></code></pre></div>
<pre><code>##        1 
## 24.58173</code></pre>
<p><strong>Measure 95% confidence interval</strong></p>
<div class="sourceCode" id="cb1005"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1005-1" data-line-number="1">testdata_result =<span class="st"> </span><span class="kw">predict</span>(<span class="dt">object =</span> stackloss.lm, testdata, <span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>);</a>
<a class="sourceLine" id="cb1005-2" data-line-number="2">testdata_result;</a></code></pre></div>
<pre><code>##        fit      lwr    upr
## 1 24.58173 20.21846 28.945</code></pre>
<p>So we are 95% confident that the mean stackloss will be between 20.21 to 28.94</p>
<p><strong>Measure 95% prediction interval</strong></p>
<div class="sourceCode" id="cb1007"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1007-1" data-line-number="1">testdata_result =<span class="st"> </span><span class="kw">predict</span>(<span class="dt">object =</span> stackloss.lm, testdata, <span class="dt">interval=</span><span class="st">&quot;prediction&quot;</span>);</a>
<a class="sourceLine" id="cb1007-2" data-line-number="2">testdata_result;</a></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 24.58173 16.4661 32.69736</code></pre>
<p>So we are 95% confident that the predicted stackloss will be between 16.46 to 32.69</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-distributions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="clustering.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
